// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

import { c, RPC, RPCStream, RPCRequestStream } from 'hrpc/runtime'
import { getEncoding } from './messages.js'

const methods = new Map([
  ['@pear-docs/initialize', 0],
  [0, '@pear-docs/initialize'],
  ['@pear-docs/list-docs', 1],
  [1, '@pear-docs/list-docs'],
  ['@pear-docs/create-doc', 2],
  [2, '@pear-docs/create-doc'],
  ['@pear-docs/join-doc', 3],
  [3, '@pear-docs/join-doc'],
  ['@pear-docs/pair-invite', 4],
  [4, '@pear-docs/pair-invite'],
  ['@pear-docs/remove-doc', 5],
  [5, '@pear-docs/remove-doc'],
  ['@pear-docs/get-doc', 6],
  [6, '@pear-docs/get-doc'],
  ['@pear-docs/watch-doc', 7],
  [7, '@pear-docs/watch-doc'],
  ['@pear-docs/apply-ops', 8],
  [8, '@pear-docs/apply-ops'],
  ['@pear-docs/update-presence', 9],
  [9, '@pear-docs/update-presence'],
  ['@pear-docs/list-invites', 10],
  [10, '@pear-docs/list-invites'],
  ['@pear-docs/create-invite', 11],
  [11, '@pear-docs/create-invite'],
  ['@pear-docs/revoke-invite', 12],
  [12, '@pear-docs/revoke-invite']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@pear-docs/initialize', getEncoding('@pear-docs-rpc/initialize-request')],
      ['@pear-docs/list-docs', getEncoding('@pear-docs-rpc/list-docs-request')],
      ['@pear-docs/create-doc', getEncoding('@pear-docs-rpc/create-doc-request')],
      ['@pear-docs/join-doc', getEncoding('@pear-docs-rpc/join-doc-request')],
      ['@pear-docs/pair-invite', getEncoding('@pear-docs-rpc/pair-invite-request')],
      ['@pear-docs/remove-doc', getEncoding('@pear-docs-rpc/remove-doc-request')],
      ['@pear-docs/get-doc', getEncoding('@pear-docs-rpc/get-doc-request')],
      ['@pear-docs/watch-doc', getEncoding('@pear-docs-rpc/watch-doc-request')],
      ['@pear-docs/apply-ops', getEncoding('@pear-docs-rpc/apply-ops-request')],
      ['@pear-docs/update-presence', getEncoding('@pear-docs-rpc/update-presence-request')],
      ['@pear-docs/list-invites', getEncoding('@pear-docs-rpc/list-invites-request')],
      ['@pear-docs/create-invite', getEncoding('@pear-docs-rpc/create-invite-request')],
      ['@pear-docs/revoke-invite', getEncoding('@pear-docs-rpc/revoke-invite-request')]
    ])
    this._responseEncodings = new Map([
      ['@pear-docs/initialize', getEncoding('@pear-docs-rpc/initialize-response')],
      ['@pear-docs/list-docs', getEncoding('@pear-docs-rpc/list-docs-response')],
      ['@pear-docs/create-doc', getEncoding('@pear-docs-rpc/create-doc-response')],
      ['@pear-docs/join-doc', getEncoding('@pear-docs-rpc/join-doc-response')],
      ['@pear-docs/pair-invite', getEncoding('@pear-docs-rpc/pair-status')],
      ['@pear-docs/remove-doc', getEncoding('@pear-docs-rpc/remove-doc-response')],
      ['@pear-docs/get-doc', getEncoding('@pear-docs-rpc/get-doc-response')],
      ['@pear-docs/watch-doc', getEncoding('@pear-docs-rpc/doc-update')],
      ['@pear-docs/apply-ops', getEncoding('@pear-docs-rpc/apply-ops-response')],
      ['@pear-docs/update-presence', getEncoding('@pear-docs-rpc/update-presence-response')],
      ['@pear-docs/list-invites', getEncoding('@pear-docs-rpc/list-invites-response')],
      ['@pear-docs/create-invite', getEncoding('@pear-docs-rpc/create-invite-response')],
      ['@pear-docs/revoke-invite', getEncoding('@pear-docs-rpc/revoke-invite-response')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
    }
    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  async initialize(args) {
    return this._call('@pear-docs/initialize', args)
  }

  async listDocs(args) {
    return this._call('@pear-docs/list-docs', args)
  }

  async createDoc(args) {
    return this._call('@pear-docs/create-doc', args)
  }

  async joinDoc(args) {
    return this._call('@pear-docs/join-doc', args)
  }

  pairInvite(args) {
    return this._callSync('@pear-docs/pair-invite', args)
  }

  async removeDoc(args) {
    return this._call('@pear-docs/remove-doc', args)
  }

  async getDoc(args) {
    return this._call('@pear-docs/get-doc', args)
  }

  watchDoc(args) {
    return this._callSync('@pear-docs/watch-doc', args)
  }

  async applyOps(args) {
    return this._call('@pear-docs/apply-ops', args)
  }

  async updatePresence(args) {
    return this._call('@pear-docs/update-presence', args)
  }

  async listInvites(args) {
    return this._call('@pear-docs/list-invites', args)
  }

  async createInvite(args) {
    return this._call('@pear-docs/create-invite', args)
  }

  async revokeInvite(args) {
    return this._call('@pear-docs/revoke-invite', args)
  }

  onInitialize(responseFn) {
    this._handlers['@pear-docs/initialize'] = responseFn
  }

  onListDocs(responseFn) {
    this._handlers['@pear-docs/list-docs'] = responseFn
  }

  onCreateDoc(responseFn) {
    this._handlers['@pear-docs/create-doc'] = responseFn
  }

  onJoinDoc(responseFn) {
    this._handlers['@pear-docs/join-doc'] = responseFn
  }

  onPairInvite(responseFn) {
    this._handlers['@pear-docs/pair-invite'] = responseFn
  }

  onRemoveDoc(responseFn) {
    this._handlers['@pear-docs/remove-doc'] = responseFn
  }

  onGetDoc(responseFn) {
    this._handlers['@pear-docs/get-doc'] = responseFn
  }

  onWatchDoc(responseFn) {
    this._handlers['@pear-docs/watch-doc'] = responseFn
  }

  onApplyOps(responseFn) {
    this._handlers['@pear-docs/apply-ops'] = responseFn
  }

  onUpdatePresence(responseFn) {
    this._handlers['@pear-docs/update-presence'] = responseFn
  }

  onListInvites(responseFn) {
    this._handlers['@pear-docs/list-invites'] = responseFn
  }

  onCreateInvite(responseFn) {
    this._handlers['@pear-docs/create-invite'] = responseFn
  }

  onRevokeInvite(responseFn) {
    this._handlers['@pear-docs/revoke-invite'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
      '@pear-docs/pair-invite',
      '@pear-docs/watch-doc'
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
    ].includes(command)
  }
}

export default HRPC
