// This file is autogenerated by the hyperschema compiler
// Schema Version: 3
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 3

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobonk/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @autobonk/invite.roles
const encoding1_4 = c.array(c.string)

// @autobonk/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
    state.end++ // max flag is 8 so always one byte

    if (m.roles) encoding1_4.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.createdBy ? 2 : 0) |
      (m.createdAt ? 4 : 0) |
      (m.revokedAt ? 8 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.roles) encoding1_4.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3,
      roles: (flags & 1) !== 0 ? encoding1_4.decode(state) : null,
      createdBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @autobonk/revoke-invite
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)

    return {
      id: r0,
      revokedAt: r1
    }
  }
}

// @autobonk/context-init
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)

    return {
      creatorKey: r0,
      index: r1,
      timestamp: r2
    }
  }
}

// @autobonk/role-def.permissions
const encoding4_1 = encoding1_4

// @autobonk/role-def
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    encoding4_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    encoding4_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding4_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: r0,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @autobonk/acl-entry.roles
const encoding5_1 = encoding1_4

// @autobonk/acl-entry
const encoding5 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.subjectKey)
    encoding5_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.subjectKey)
    encoding5_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding5_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: r0,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @bonk-docs/metadata
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 32 so always one byte

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    c.uint.preencode(state, m.createdAt)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.creatorKey) c.fixed32.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.rev)
    if (m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (m.lockedBy) c.fixed32.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.updatedAt ? 4 : 0) |
      (m.creatorKey ? 8 : 0) |
      (m.lockedAt ? 16 : 0) |
      (m.lockedBy ? 32 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    c.uint.encode(state, m.createdAt)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.creatorKey) c.fixed32.encode(state, m.creatorKey)
    c.uint.encode(state, m.rev)
    if (m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (m.lockedBy) c.fixed32.encode(state, m.lockedBy)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: c.uint.decode(state),
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      creatorKey: (flags & 8) !== 0 ? c.fixed32.decode(state) : null,
      rev: c.uint.decode(state),
      lockedAt: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      lockedBy: (flags & 32) !== 0 ? c.fixed32.decode(state) : null
    }
  }
}

// @bonk-docs/update
const encoding7 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = m.sessionId ? 1 : 0

    c.uint.encode(state, m.rev)
    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      clientId: r1,
      timestamp: r2,
      data: r3,
      sessionId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/update-entry
const encoding8 = {
  preencode(state, m) {
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = m.sessionId ? 1 : 0

    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      clientId: r0,
      timestamp: r1,
      data: r2,
      sessionId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/snapshot
const encoding9 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 4 so always one byte

    if (m.compression) c.string.preencode(state, m.compression)
    c.buffer.preencode(state, m.data)
    if (m.hash) c.buffer.preencode(state, m.hash)
    if (m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags =
      (m.compression ? 1 : 0) |
      (m.hash ? 2 : 0) |
      (m.stateVector ? 4 : 0)

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.compression) c.string.encode(state, m.compression)
    c.buffer.encode(state, m.data)
    if (m.hash) c.buffer.encode(state, m.hash)
    if (m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      createdAt: r1,
      compression: (flags & 1) !== 0 ? c.string.decode(state) : null,
      data: c.buffer.decode(state),
      hash: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      stateVector: (flags & 4) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs/awareness
const encoding10 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.clientId) c.string.preencode(state, m.clientId)
  },
  encode(state, m) {
    const flags = m.clientId ? 1 : 0

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.clientId) c.string.encode(state, m.clientId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      timestamp: r1,
      data: r2,
      clientId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/awareness-entry
const encoding11 = {
  preencode(state, m) {
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.clientId) c.string.preencode(state, m.clientId)
  },
  encode(state, m) {
    const flags = m.clientId ? 1 : 0

    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.clientId) c.string.encode(state, m.clientId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      timestamp: r0,
      data: r1,
      clientId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @local/doc
const encoding12 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.encryptionKey)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 64 so always one byte

    if (m.joinedAt) c.uint.preencode(state, m.joinedAt)
    if (m.title) c.string.preencode(state, m.title)
    if (m.lastRevision) c.uint.preencode(state, m.lastRevision)
    if (m.lastOpenedAt) c.uint.preencode(state, m.lastOpenedAt)
    if (m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (m.lockedBy) c.string.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    const flags =
      (m.joinedAt ? 1 : 0) |
      (m.isCreator ? 2 : 0) |
      (m.title ? 4 : 0) |
      (m.lastRevision ? 8 : 0) |
      (m.lastOpenedAt ? 16 : 0) |
      (m.lockedAt ? 32 : 0) |
      (m.lockedBy ? 64 : 0)

    c.string.encode(state, m.key)
    c.string.encode(state, m.encryptionKey)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.joinedAt) c.uint.encode(state, m.joinedAt)
    if (m.title) c.string.encode(state, m.title)
    if (m.lastRevision) c.uint.encode(state, m.lastRevision)
    if (m.lastOpenedAt) c.uint.encode(state, m.lastOpenedAt)
    if (m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (m.lockedBy) c.string.encode(state, m.lockedBy)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      encryptionKey: r1,
      createdAt: r2,
      joinedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      isCreator: (flags & 2) !== 0,
      title: (flags & 4) !== 0 ? c.string.decode(state) : null,
      lastRevision: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      lastOpenedAt: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      lockedAt: (flags & 32) !== 0 ? c.uint.decode(state) : 0,
      lockedBy: (flags & 64) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-capabilities.roles
const encoding13_3 = encoding1_4

// @bonk-docs-rpc/doc-capabilities
const encoding13 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.roles) encoding13_3.preencode(state, m.roles)
  },
  encode(state, m) {
    const flags =
      (m.canEdit ? 1 : 0) |
      (m.canComment ? 2 : 0) |
      (m.canInvite ? 4 : 0) |
      (m.roles ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.roles) encoding13_3.encode(state, m.roles)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      canEdit: (flags & 1) !== 0,
      canComment: (flags & 2) !== 0,
      canInvite: (flags & 4) !== 0,
      roles: (flags & 8) !== 0 ? encoding13_3.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-update-entry
const encoding14 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.rev) c.uint.preencode(state, m.rev)
    c.string.preencode(state, m.clientId)
    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    const flags =
      (m.rev ? 1 : 0) |
      (m.timestamp ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.rev) c.uint.encode(state, m.rev)
    c.string.encode(state, m.clientId)
    if (m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      rev: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      clientId: c.string.decode(state),
      timestamp: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state)
    }
  }
}

// @bonk-docs-rpc/doc-update.capabilities
const encoding15_4 = c.frame(encoding13)
// @bonk-docs-rpc/doc-update.updates
const encoding15_8 = c.array(c.frame(encoding14))

// @bonk-docs-rpc/doc-update
const encoding15 = {
  preencode(state, m) {
    const flags =
      (m.updatedAt ? 1 : 0) |
      (m.title ? 2 : 0) |
      (m.capabilities ? 4 : 0) |
      (m.lockedAt ? 8 : 0) |
      (m.lockedBy ? 16 : 0) |
      (m.syncUpdate ? 32 : 0) |
      (m.updates ? 64 : 0) |
      (m.awareness ? 128 : 0) |
      ((version >= 2 && m.writerKey) ? 256 : 0)

    c.string.preencode(state, m.key)
    c.uint.preencode(state, m.revision)
    c.uint.preencode(state, flags)

    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.title) c.string.preencode(state, m.title)
    if (m.capabilities) encoding15_4.preencode(state, m.capabilities)
    if (m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (m.lockedBy) c.string.preencode(state, m.lockedBy)
    if (m.syncUpdate) c.buffer.preencode(state, m.syncUpdate)
    if (m.updates) encoding15_8.preencode(state, m.updates)
    if (m.awareness) c.buffer.preencode(state, m.awareness)
    if (version >= 2 && m.writerKey) c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    const flags =
      (m.updatedAt ? 1 : 0) |
      (m.title ? 2 : 0) |
      (m.capabilities ? 4 : 0) |
      (m.lockedAt ? 8 : 0) |
      (m.lockedBy ? 16 : 0) |
      (m.syncUpdate ? 32 : 0) |
      (m.updates ? 64 : 0) |
      (m.awareness ? 128 : 0) |
      ((version >= 2 && m.writerKey) ? 256 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, m.revision)
    c.uint.encode(state, flags)

    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.title) c.string.encode(state, m.title)
    if (m.capabilities) encoding15_4.encode(state, m.capabilities)
    if (m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (m.lockedBy) c.string.encode(state, m.lockedBy)
    if (m.syncUpdate) c.buffer.encode(state, m.syncUpdate)
    if (m.updates) encoding15_8.encode(state, m.updates)
    if (m.awareness) c.buffer.encode(state, m.awareness)
    if (version >= 2 && m.writerKey) c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      revision: r1,
      updatedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      title: (flags & 2) !== 0 ? c.string.decode(state) : null,
      capabilities: (flags & 4) !== 0 ? encoding15_4.decode(state) : null,
      lockedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      lockedBy: (flags & 16) !== 0 ? c.string.decode(state) : null,
      syncUpdate: (flags & 32) !== 0 ? c.buffer.decode(state) : null,
      updates: (flags & 64) !== 0 ? encoding15_8.decode(state) : null,
      awareness: (flags & 128) !== 0 ? c.buffer.decode(state) : null,
      writerKey: (version >= 2 && (flags & 256) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-invite.roles
const encoding16_2 = encoding1_4

// @bonk-docs-rpc/doc-invite
const encoding16 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 16 so always one byte

    if (m.roles) encoding16_2.preencode(state, m.roles)
    if (m.createdBy) c.string.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
    if (m.expiresAt) c.int.preencode(state, m.expiresAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.createdBy ? 2 : 0) |
      (m.createdAt ? 4 : 0) |
      (m.revokedAt ? 8 : 0) |
      (m.expiresAt ? 16 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (m.roles) encoding16_2.encode(state, m.roles)
    if (m.createdBy) c.string.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
    if (m.expiresAt) c.int.encode(state, m.expiresAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      roles: (flags & 1) !== 0 ? encoding16_2.decode(state) : null,
      createdBy: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      expiresAt: (flags & 16) !== 0 ? c.int.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/initialize-request
const encoding17 = {
  preencode(state, m) {

  },
  encode(state, m) {

  },
  decode(state) {
    return {
    }
  }
}

// @bonk-docs-rpc/initialize-response.docs
const encoding18_0 = c.array(c.frame(encoding12))

// @bonk-docs-rpc/initialize-response
const encoding18 = {
  preencode(state, m) {
    encoding18_0.preencode(state, m.docs)
    state.end++ // max flag is 2 so always one byte

    if (m.activeDoc) c.string.preencode(state, m.activeDoc)
    if (version >= 3 && m.identity) encoding18_2.preencode(state, m.identity)
  },
  encode(state, m) {
    const flags =
      (m.activeDoc ? 1 : 0) |
      ((version >= 3 && m.identity) ? 2 : 0)

    encoding18_0.encode(state, m.docs)
    c.uint.encode(state, flags)

    if (m.activeDoc) c.string.encode(state, m.activeDoc)
    if (version >= 3 && m.identity) encoding18_2.encode(state, m.identity)
  },
  decode(state) {
    const r0 = encoding18_0.decode(state)
    const flags = c.uint.decode(state)

    return {
      docs: r0,
      activeDoc: (flags & 1) !== 0 ? c.string.decode(state) : null,
      identity: (version >= 3 && (flags & 2) !== 0) ? encoding18_2.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/list-docs-request
const encoding19 = encoding17

// @bonk-docs-rpc/list-docs-response.docs
const encoding20_0 = encoding18_0

// @bonk-docs-rpc/list-docs-response
const encoding20 = {
  preencode(state, m) {
    encoding20_0.preencode(state, m.docs)
  },
  encode(state, m) {
    encoding20_0.encode(state, m.docs)
  },
  decode(state) {
    const r0 = encoding20_0.decode(state)

    return {
      docs: r0
    }
  }
}

// @bonk-docs-rpc/create-doc-request
const encoding21 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = m.title ? 1 : 0

    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      title: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/create-doc-response.doc
const encoding22_0 = c.frame(encoding12)

// @bonk-docs-rpc/create-doc-response
const encoding22 = {
  preencode(state, m) {
    encoding22_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    encoding22_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = encoding22_0.decode(state)
    const r1 = c.string.decode(state)

    return {
      doc: r0,
      writerKey: r1
    }
  }
}

// @bonk-docs-rpc/join-doc-request
const encoding23 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 1 so always one byte

    if (m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = m.title ? 1 : 0

    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      invite: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/join-doc-response.doc
const encoding24_0 = encoding22_0

// @bonk-docs-rpc/join-doc-response
const encoding24 = {
  preencode(state, m) {
    encoding24_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    encoding24_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = encoding24_0.decode(state)
    const r1 = c.string.decode(state)

    return {
      doc: r0,
      writerKey: r1
    }
  }
}

// @bonk-docs-rpc/remove-doc-request
const encoding25 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      key: r0
    }
  }
}

// @bonk-docs-rpc/remove-doc-response
const encoding26 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.removed ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      removed: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/rename-doc-request
const encoding27 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = m.title ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/rename-doc-response
const encoding28 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.title)
    state.end++ // max flag is 1 so always one byte

    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.updatedAt ? 1 : 0

    c.string.encode(state, m.key)
    c.string.encode(state, m.title)
    c.uint.encode(state, flags)

    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      title: r1,
      updatedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/lock-doc-request
const encoding29 = encoding25

// @bonk-docs-rpc/lock-doc-response
const encoding30 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.uint.preencode(state, m.lockedAt)
    c.string.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.uint.encode(state, m.lockedAt)
    c.string.encode(state, m.lockedBy)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      key: r0,
      lockedAt: r1,
      lockedBy: r2
    }
  }
}

// @bonk-docs-rpc/get-doc-request
const encoding31 = encoding25

// @bonk-docs-rpc/get-doc-response.doc
const encoding32_0 = encoding22_0

// @bonk-docs-rpc/get-doc-response
const encoding32 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.doc) encoding32_0.preencode(state, m.doc)
    if (version >= 2 && m.writerKey) c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    const flags =
      (m.doc ? 1 : 0) |
      ((version >= 2 && m.writerKey) ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.doc) encoding32_0.encode(state, m.doc)
    if (version >= 2 && m.writerKey) c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      doc: (flags & 1) !== 0 ? encoding32_0.decode(state) : null,
      writerKey: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/watch-doc-request
const encoding33 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags = m.stateVector ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      stateVector: (flags & 1) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/apply-updates-request.updates
const encoding34_1 = encoding15_8

// @bonk-docs-rpc/apply-updates-request
const encoding34 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    encoding34_1.preencode(state, m.updates)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    encoding34_1.encode(state, m.updates)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding34_1.decode(state)

    return {
      key: r0,
      updates: r1
    }
  }
}

// @bonk-docs-rpc/apply-updates-response
const encoding35 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.revision) c.uint.preencode(state, m.revision)
    if (m.error) c.string.preencode(state, m.error)
  },
  encode(state, m) {
    const flags =
      (m.accepted ? 1 : 0) |
      (m.revision ? 2 : 0) |
      (m.error ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.revision) c.uint.encode(state, m.revision)
    if (m.error) c.string.encode(state, m.error)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      accepted: (flags & 1) !== 0,
      revision: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      error: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/apply-awareness-request
const encoding36 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.buffer.preencode(state, m.update)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.buffer.encode(state, m.update)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      key: r0,
      update: r1
    }
  }
}

// @bonk-docs-rpc/apply-awareness-response
const encoding37 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.accepted ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      accepted: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/list-invites-request
const encoding38 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.includeRevoked ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      includeRevoked: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/list-invites-response.invites
const encoding39_0 = c.array(c.frame(encoding16))

// @bonk-docs-rpc/list-invites-response
const encoding39 = {
  preencode(state, m) {
    encoding39_0.preencode(state, m.invites)
  },
  encode(state, m) {
    encoding39_0.encode(state, m.invites)
  },
  decode(state) {
    const r0 = encoding39_0.decode(state)

    return {
      invites: r0
    }
  }
}

// @bonk-docs-rpc/create-invite-request.roles
const encoding40_1 = encoding1_4

// @bonk-docs-rpc/create-invite-request
const encoding40 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 2 so always one byte

    if (m.roles) encoding40_1.preencode(state, m.roles)
    if (m.expiresAt) c.uint.preencode(state, m.expiresAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.expiresAt ? 2 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.roles) encoding40_1.encode(state, m.roles)
    if (m.expiresAt) c.uint.encode(state, m.expiresAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      roles: (flags & 1) !== 0 ? encoding40_1.decode(state) : null,
      expiresAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/create-invite-response
const encoding41 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
    c.string.preencode(state, m.inviteId)
  },
  encode(state, m) {
    c.string.encode(state, m.invite)
    c.string.encode(state, m.inviteId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      invite: r0,
      inviteId: r1
    }
  }
}

// @bonk-docs-rpc/revoke-invite-request
const encoding42 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.inviteId)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.string.encode(state, m.inviteId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      key: r0,
      inviteId: r1
    }
  }
}

// @bonk-docs-rpc/revoke-invite-response
const encoding43 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.revoked ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      revoked: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/pair-invite-request
const encoding44 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
  },
  encode(state, m) {
    c.string.encode(state, m.invite)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      invite: r0
    }
  }
}

// @bonk-docs-rpc/pair-status.doc
const encoding45_3 = encoding22_0

// @bonk-docs-rpc/pair-status
const encoding45 = {
  preencode(state, m) {
    c.string.preencode(state, m.state)
    state.end++ // max flag is 8 so always one byte

    if (m.message) c.string.preencode(state, m.message)
    if (m.progress) c.uint.preencode(state, m.progress)
    if (m.doc) encoding45_3.preencode(state, m.doc)
    if (m.writerKey) c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    const flags =
      (m.message ? 1 : 0) |
      (m.progress ? 2 : 0) |
      (m.doc ? 4 : 0) |
      (m.writerKey ? 8 : 0)

    c.string.encode(state, m.state)
    c.uint.encode(state, flags)

    if (m.message) c.string.encode(state, m.message)
    if (m.progress) c.uint.encode(state, m.progress)
    if (m.doc) encoding45_3.encode(state, m.doc)
    if (m.writerKey) c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      state: r0,
      message: (flags & 1) !== 0 ? c.string.decode(state) : null,
      progress: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      doc: (flags & 4) !== 0 ? encoding45_3.decode(state) : null,
      writerKey: (flags & 8) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/identity-profile
const encoding46 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (version >= 3 && m.displayName) c.string.preencode(state, m.displayName)
    if (version >= 3 && m.bio) c.string.preencode(state, m.bio)
    if (version >= 3 && m.updatedAt) c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 3 && m.displayName) ? 1 : 0) |
      ((version >= 3 && m.bio) ? 2 : 0) |
      ((version >= 3 && m.updatedAt) ? 4 : 0)

    c.uint.encode(state, flags)

    if (version >= 3 && m.displayName) c.string.encode(state, m.displayName)
    if (version >= 3 && m.bio) c.string.encode(state, m.bio)
    if (version >= 3 && m.updatedAt) c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      displayName: (version >= 3 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      bio: (version >= 3 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      updatedAt: (version >= 3 && (flags & 4) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/identity-summary.profile
const encoding47_2 = c.frame(encoding46)

// @bonk-docs-rpc/identity-summary
const encoding47 = {
  preencode(state, m) {
    c.string.preencode(state, m.identityKey)
    c.string.preencode(state, m.writerKey)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.profile) encoding47_2.preencode(state, m.profile)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.profile) ? 1 : 0

    c.string.encode(state, m.identityKey)
    c.string.encode(state, m.writerKey)
    c.uint.encode(state, flags)

    if (version >= 3 && m.profile) encoding47_2.encode(state, m.profile)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      identityKey: r0,
      writerKey: r1,
      profile: (version >= 3 && (flags & 1) !== 0) ? encoding47_2.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/get-identity-request
const encoding48 = encoding17

// @bonk-docs-rpc/get-identity-response
const encoding49 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.identity) encoding49_0.preencode(state, m.identity)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.identity) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 3 && m.identity) encoding49_0.encode(state, m.identity)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      identity: (version >= 3 && (flags & 1) !== 0) ? encoding49_0.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/link-identity-request
const encoding50 = encoding44

// @bonk-docs-rpc/link-identity-response
const encoding51 = {
  preencode(state, m) {
    encoding51_0.preencode(state, m.identity)
  },
  encode(state, m) {
    encoding51_0.encode(state, m.identity)
  },
  decode(state) {
    const r0 = encoding51_0.decode(state)

    return {
      identity: r0
    }
  }
}

// @bonk-docs-rpc/initialize-response.identity, deferred due to recusive use
const encoding18_2 = c.frame(encoding47)
// @bonk-docs-rpc/get-identity-response.identity, deferred due to recusive use
const encoding49_0 = encoding18_2
// @bonk-docs-rpc/link-identity-response.identity, deferred due to recusive use
const encoding51_0 = encoding18_2

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autobonk/writer':
      return encoding0
    case '@autobonk/invite':
      return encoding1
    case '@autobonk/revoke-invite':
      return encoding2
    case '@autobonk/context-init':
      return encoding3
    case '@autobonk/role-def':
      return encoding4
    case '@autobonk/acl-entry':
      return encoding5
    case '@bonk-docs/metadata':
      return encoding6
    case '@bonk-docs/update':
      return encoding7
    case '@bonk-docs/update-entry':
      return encoding8
    case '@bonk-docs/snapshot':
      return encoding9
    case '@bonk-docs/awareness':
      return encoding10
    case '@bonk-docs/awareness-entry':
      return encoding11
    case '@local/doc':
      return encoding12
    case '@bonk-docs-rpc/doc-capabilities':
      return encoding13
    case '@bonk-docs-rpc/doc-update-entry':
      return encoding14
    case '@bonk-docs-rpc/doc-update':
      return encoding15
    case '@bonk-docs-rpc/doc-invite':
      return encoding16
    case '@bonk-docs-rpc/initialize-request':
      return encoding17
    case '@bonk-docs-rpc/initialize-response':
      return encoding18
    case '@bonk-docs-rpc/list-docs-request':
      return encoding19
    case '@bonk-docs-rpc/list-docs-response':
      return encoding20
    case '@bonk-docs-rpc/create-doc-request':
      return encoding21
    case '@bonk-docs-rpc/create-doc-response':
      return encoding22
    case '@bonk-docs-rpc/join-doc-request':
      return encoding23
    case '@bonk-docs-rpc/join-doc-response':
      return encoding24
    case '@bonk-docs-rpc/remove-doc-request':
      return encoding25
    case '@bonk-docs-rpc/remove-doc-response':
      return encoding26
    case '@bonk-docs-rpc/rename-doc-request':
      return encoding27
    case '@bonk-docs-rpc/rename-doc-response':
      return encoding28
    case '@bonk-docs-rpc/lock-doc-request':
      return encoding29
    case '@bonk-docs-rpc/lock-doc-response':
      return encoding30
    case '@bonk-docs-rpc/get-doc-request':
      return encoding31
    case '@bonk-docs-rpc/get-doc-response':
      return encoding32
    case '@bonk-docs-rpc/watch-doc-request':
      return encoding33
    case '@bonk-docs-rpc/apply-updates-request':
      return encoding34
    case '@bonk-docs-rpc/apply-updates-response':
      return encoding35
    case '@bonk-docs-rpc/apply-awareness-request':
      return encoding36
    case '@bonk-docs-rpc/apply-awareness-response':
      return encoding37
    case '@bonk-docs-rpc/list-invites-request':
      return encoding38
    case '@bonk-docs-rpc/list-invites-response':
      return encoding39
    case '@bonk-docs-rpc/create-invite-request':
      return encoding40
    case '@bonk-docs-rpc/create-invite-response':
      return encoding41
    case '@bonk-docs-rpc/revoke-invite-request':
      return encoding42
    case '@bonk-docs-rpc/revoke-invite-response':
      return encoding43
    case '@bonk-docs-rpc/pair-invite-request':
      return encoding44
    case '@bonk-docs-rpc/pair-status':
      return encoding45
    case '@bonk-docs-rpc/identity-profile':
      return encoding46
    case '@bonk-docs-rpc/identity-summary':
      return encoding47
    case '@bonk-docs-rpc/get-identity-request':
      return encoding48
    case '@bonk-docs-rpc/get-identity-response':
      return encoding49
    case '@bonk-docs-rpc/link-identity-request':
      return encoding50
    case '@bonk-docs-rpc/link-identity-response':
      return encoding51
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
