// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

import { IndexEncoder, c, b4a } from 'hyperdb/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const versions = { schema: version, db: 1 }

// '@bonkdocs-doc/metadata' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@bonkdocs-doc/metadata' value encoding
const collection0_enc = getEncoding('@bonkdocs-doc/metadata/hyperdb#0')

// '@bonkdocs-doc/metadata' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.id = key[0]
  return record
}
// '@bonkdocs-doc/metadata' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@bonkdocs-doc/metadata'
const collection0 = {
  name: '@bonkdocs-doc/metadata',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@spaces/writers' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 1 })

function collection1_indexify (record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@spaces/writers' value encoding
const collection1_enc = getEncoding('@spaces/writer/hyperdb#1')

// '@spaces/writers' reconstruction function
function collection1_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.key = key[0]
  return record
}
// '@spaces/writers' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@spaces/writers'
const collection1 = {
  name: '@spaces/writers',
  id: 1,
  version: 1,
  encodeKey (record) {
    const key = [record.key]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@spaces/invites' collection key
const collection2_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 2 })

function collection2_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@spaces/invites' value encoding
const collection2_enc = getEncoding('@spaces/invite/hyperdb#2')

// '@spaces/invites' reconstruction function
function collection2_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection2.decodedVersion = c.uint.decode(state)
  const record = collection2_enc.decode(state)
  record.id = key[0]
  return record
}
// '@spaces/invites' key reconstruction function
function collection2_reconstruct_key (keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@spaces/invites'
const collection2 = {
  name: '@spaces/invites',
  id: 2,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection2_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection2_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection2_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@spaces/space-init' collection key
const collection3_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 3 })

function collection3_indexify (record) {
  const a = record.creatorKey
  return a === undefined ? [] : [a]
}

// '@spaces/space-init' value encoding
const collection3_enc = getEncoding('@spaces/space-init/hyperdb#3')

// '@spaces/space-init' reconstruction function
function collection3_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection3_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection3.decodedVersion = c.uint.decode(state)
  const record = collection3_enc.decode(state)
  record.creatorKey = key[0]
  return record
}
// '@spaces/space-init' key reconstruction function
function collection3_reconstruct_key (keyBuf) {
  const key = collection3_key.decode(keyBuf)
  return {
    creatorKey: key[0]
  }
}

// '@spaces/space-init'
const collection3 = {
  name: '@spaces/space-init',
  id: 3,
  version: 1,
  encodeKey (record) {
    const key = [record.creatorKey]
    return collection3_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection3_key.encodeRange({
      gt: gt ? collection3_indexify(gt) : null,
      lt: lt ? collection3_indexify(lt) : null,
      gte: gte ? collection3_indexify(gte) : null,
      lte: lte ? collection3_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection3_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection3_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection3_reconstruct,
  reconstructKey: collection3_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@spaces/roles' collection key
const collection4_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 4 })

function collection4_indexify (record) {
  const a = record.name
  return a === undefined ? [] : [a]
}

// '@spaces/roles' value encoding
const collection4_enc = getEncoding('@spaces/role-def/hyperdb#4')

// '@spaces/roles' reconstruction function
function collection4_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection4_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection4.decodedVersion = c.uint.decode(state)
  const record = collection4_enc.decode(state)
  record.name = key[0]
  return record
}
// '@spaces/roles' key reconstruction function
function collection4_reconstruct_key (keyBuf) {
  const key = collection4_key.decode(keyBuf)
  return {
    name: key[0]
  }
}

// '@spaces/roles'
const collection4 = {
  name: '@spaces/roles',
  id: 4,
  version: 1,
  encodeKey (record) {
    const key = [record.name]
    return collection4_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection4_key.encodeRange({
      gt: gt ? collection4_indexify(gt) : null,
      lt: lt ? collection4_indexify(lt) : null,
      gte: gte ? collection4_indexify(gte) : null,
      lte: lte ? collection4_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection4_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection4_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection4_reconstruct,
  reconstructKey: collection4_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@spaces/acl' collection key
const collection5_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 5 })

function collection5_indexify (record) {
  const a = record.subjectKey
  return a === undefined ? [] : [a]
}

// '@spaces/acl' value encoding
const collection5_enc = getEncoding('@spaces/acl-entry/hyperdb#5')

// '@spaces/acl' reconstruction function
function collection5_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection5_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection5.decodedVersion = c.uint.decode(state)
  const record = collection5_enc.decode(state)
  record.subjectKey = key[0]
  return record
}
// '@spaces/acl' key reconstruction function
function collection5_reconstruct_key (keyBuf) {
  const key = collection5_key.decode(keyBuf)
  return {
    subjectKey: key[0]
  }
}

// '@spaces/acl'
const collection5 = {
  name: '@spaces/acl',
  id: 5,
  version: 1,
  encodeKey (record) {
    const key = [record.subjectKey]
    return collection5_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection5_key.encodeRange({
      gt: gt ? collection5_indexify(gt) : null,
      lt: lt ? collection5_indexify(lt) : null,
      gte: gte ? collection5_indexify(gte) : null,
      lte: lte ? collection5_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection5_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection5_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection5_reconstruct,
  reconstructKey: collection5_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@bonk-docs/yjs-updates' collection key
const collection6_key = new IndexEncoder([
  IndexEncoder.UINT
], { prefix: 6 })

function collection6_indexify (record) {
  const a = record.rev
  return a === undefined ? [] : [a]
}

// '@bonk-docs/yjs-updates' value encoding
const collection6_enc = getEncoding('@bonk-docs/yjs-update/hyperdb#6')

// '@bonk-docs/yjs-updates' reconstruction function
function collection6_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection6_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection6.decodedVersion = c.uint.decode(state)
  const record = collection6_enc.decode(state)
  record.rev = key[0]
  return record
}
// '@bonk-docs/yjs-updates' key reconstruction function
function collection6_reconstruct_key (keyBuf) {
  const key = collection6_key.decode(keyBuf)
  return {
    rev: key[0]
  }
}

// '@bonk-docs/yjs-updates'
const collection6 = {
  name: '@bonk-docs/yjs-updates',
  id: 6,
  version: 1,
  encodeKey (record) {
    const key = [record.rev]
    return collection6_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection6_key.encodeRange({
      gt: gt ? collection6_indexify(gt) : null,
      lt: lt ? collection6_indexify(lt) : null,
      gte: gte ? collection6_indexify(gte) : null,
      lte: lte ? collection6_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection6_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection6_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection6_reconstruct,
  reconstructKey: collection6_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@bonk-docs/yjs-snapshots' collection key
const collection7_key = new IndexEncoder([
  IndexEncoder.UINT
], { prefix: 7 })

function collection7_indexify (record) {
  const a = record.rev
  return a === undefined ? [] : [a]
}

// '@bonk-docs/yjs-snapshots' value encoding
const collection7_enc = getEncoding('@bonk-docs/yjs-snapshot/hyperdb#7')

// '@bonk-docs/yjs-snapshots' reconstruction function
function collection7_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection7_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection7.decodedVersion = c.uint.decode(state)
  const record = collection7_enc.decode(state)
  record.rev = key[0]
  return record
}
// '@bonk-docs/yjs-snapshots' key reconstruction function
function collection7_reconstruct_key (keyBuf) {
  const key = collection7_key.decode(keyBuf)
  return {
    rev: key[0]
  }
}

// '@bonk-docs/yjs-snapshots'
const collection7 = {
  name: '@bonk-docs/yjs-snapshots',
  id: 7,
  version: 1,
  encodeKey (record) {
    const key = [record.rev]
    return collection7_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection7_key.encodeRange({
      gt: gt ? collection7_indexify(gt) : null,
      lt: lt ? collection7_indexify(lt) : null,
      gte: gte ? collection7_indexify(gte) : null,
      lte: lte ? collection7_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection7_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection7_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection7_reconstruct,
  reconstructKey: collection7_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@bonk-docs/yjs-awareness' collection key
const collection8_key = new IndexEncoder([
  IndexEncoder.UINT
], { prefix: 8 })

function collection8_indexify (record) {
  const a = record.rev
  return a === undefined ? [] : [a]
}

// '@bonk-docs/yjs-awareness' value encoding
const collection8_enc = getEncoding('@bonk-docs/yjs-awareness/hyperdb#8')

// '@bonk-docs/yjs-awareness' reconstruction function
function collection8_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection8_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection8.decodedVersion = c.uint.decode(state)
  const record = collection8_enc.decode(state)
  record.rev = key[0]
  return record
}
// '@bonk-docs/yjs-awareness' key reconstruction function
function collection8_reconstruct_key (keyBuf) {
  const key = collection8_key.decode(keyBuf)
  return {
    rev: key[0]
  }
}

// '@bonk-docs/yjs-awareness'
const collection8 = {
  name: '@bonk-docs/yjs-awareness',
  id: 8,
  version: 1,
  encodeKey (record) {
    const key = [record.rev]
    return collection8_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection8_key.encodeRange({
      gt: gt ? collection8_indexify(gt) : null,
      lt: lt ? collection8_indexify(lt) : null,
      gte: gte ? collection8_indexify(gte) : null,
      lte: lte ? collection8_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection8_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection8_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection8_reconstruct,
  reconstructKey: collection8_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@bonk-docs/locks' collection key
const collection9_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 9 })

function collection9_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@bonk-docs/locks' value encoding
const collection9_enc = getEncoding('@bonk-docs/lock/hyperdb#9')

// '@bonk-docs/locks' reconstruction function
function collection9_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection9_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection9.decodedVersion = c.uint.decode(state)
  const record = collection9_enc.decode(state)
  record.id = key[0]
  return record
}
// '@bonk-docs/locks' key reconstruction function
function collection9_reconstruct_key (keyBuf) {
  const key = collection9_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@bonk-docs/locks'
const collection9 = {
  name: '@bonk-docs/locks',
  id: 9,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection9_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection9_key.encodeRange({
      gt: gt ? collection9_indexify(gt) : null,
      lt: lt ? collection9_indexify(lt) : null,
      gte: gte ? collection9_indexify(gte) : null,
      lte: lte ? collection9_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection9_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection9_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection9_reconstruct,
  reconstructKey: collection9_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

const collections = [
  collection0,
  collection1,
  collection2,
  collection3,
  collection4,
  collection5,
  collection6,
  collection7,
  collection8,
  collection9
]

const indexes = [
]

export default { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@bonkdocs-doc/metadata': return collection0
    case '@spaces/writers': return collection1
    case '@spaces/invites': return collection2
    case '@spaces/space-init': return collection3
    case '@spaces/roles': return collection4
    case '@spaces/acl': return collection5
    case '@bonk-docs/yjs-updates': return collection6
    case '@bonk-docs/yjs-snapshots': return collection7
    case '@bonk-docs/yjs-awareness': return collection8
    case '@bonk-docs/locks': return collection9
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    default: return null
  }
}
