// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @spaces/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @spaces/invite.roles
const encoding1_5 = c.array(c.string)

// @spaces/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    state.end++ // max flag is 64 so always one byte

    if (m.invite) c.buffer.preencode(state, m.invite)
    if (m.publicKey) c.buffer.preencode(state, m.publicKey)
    if (m.secretHash) c.buffer.preencode(state, m.secretHash)
    c.int.preencode(state, m.expires)
    if (m.roles) encoding1_5.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.invite ? 1 : 0) |
      (m.publicKey ? 2 : 0) |
      (m.secretHash ? 4 : 0) |
      (m.roles ? 8 : 0) |
      (m.createdBy ? 16 : 0) |
      (m.createdAt ? 32 : 0) |
      (m.revokedAt ? 64 : 0)

    c.buffer.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.invite) c.buffer.encode(state, m.invite)
    if (m.publicKey) c.buffer.encode(state, m.publicKey)
    if (m.secretHash) c.buffer.encode(state, m.secretHash)
    c.int.encode(state, m.expires)
    if (m.roles) encoding1_5.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      publicKey: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      secretHash: (flags & 4) !== 0 ? c.buffer.decode(state) : null,
      expires: c.int.decode(state),
      roles: (flags & 8) !== 0 ? encoding1_5.decode(state) : null,
      createdBy: (flags & 16) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 32) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 64) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @spaces/accept-invite.roles
const encoding2_5 = encoding1_5

// @spaces/accept-invite
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.secret)
    c.uint.preencode(state, m.acceptedAt)
    state.end++ // max flag is 4 so always one byte

    if (m.roles) encoding2_5.preencode(state, m.roles)
  },
  encode(state, m) {
    const flags = (m.isIndexer ? 1 : 0) | (m.optimistic ? 2 : 0) | (m.roles ? 4 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.secret)
    c.uint.encode(state, m.acceptedAt)
    c.uint.encode(state, flags)

    if (m.roles) encoding2_5.encode(state, m.roles)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      secret: r1,
      acceptedAt: r2,
      isIndexer: (flags & 1) !== 0,
      optimistic: (flags & 2) !== 0,
      roles: (flags & 4) !== 0 ? encoding2_5.decode(state) : null
    }
  }
}

// @spaces/revoke-invite
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)

    return {
      id: r0,
      revokedAt: r1
    }
  }
}

// @spaces/space-init
const encoding4 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.version)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.version)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)

    return {
      creatorKey: r0,
      version: r1,
      index: r2,
      timestamp: r3
    }
  }
}

// @spaces/role-def.permissions
const encoding5_1 = encoding1_5

// @spaces/role-def
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    encoding5_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    encoding5_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding5_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: r0,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @spaces/acl-entry.roles
const encoding6_1 = encoding1_5

// @spaces/acl-entry
const encoding6 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.subjectKey)
    encoding6_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.subjectKey)
    encoding6_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding6_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: r0,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @bonk-docs/yjs-update
const encoding7 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = m.sessionId ? 1 : 0

    c.uint.encode(state, m.rev)
    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      clientId: r1,
      timestamp: r2,
      data: r3,
      sessionId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-update-entry
const encoding8 = {
  preencode(state, m) {
    c.string.preencode(state, m.clientId)
    state.end++ // max flag is 2 so always one byte

    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    if (m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = (m.timestamp ? 1 : 0) | (m.sessionId ? 2 : 0)

    c.string.encode(state, m.clientId)
    c.uint.encode(state, flags)

    if (m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    if (m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      clientId: r0,
      timestamp: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state),
      sessionId: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-snapshot
const encoding9 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.createdAt)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags = m.stateVector ? 1 : 0

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.createdAt)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      createdAt: r1,
      data: r2,
      stateVector: (flags & 1) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-awareness
const encoding10 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.clientId) c.string.preencode(state, m.clientId)
  },
  encode(state, m) {
    const flags = m.clientId ? 1 : 0

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.clientId) c.string.encode(state, m.clientId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      timestamp: r1,
      data: r2,
      clientId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-awareness-entry
const encoding11 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    if (m.clientId) c.string.preencode(state, m.clientId)
  },
  encode(state, m) {
    const flags = (m.timestamp ? 1 : 0) | (m.clientId ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    if (m.clientId) c.string.encode(state, m.clientId)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      timestamp: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state),
      clientId: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/lock
const encoding12 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.buffer.preencode(state, m.ownerKey)
    c.uint.preencode(state, m.acquiredAt)
    state.end++ // max flag is 4 so always one byte

    if (m.expiresAt) c.uint.preencode(state, m.expiresAt)
    if (m.releasedAt) c.uint.preencode(state, m.releasedAt)
    c.uint.preencode(state, m.rev)
    if (m.metadata) c.string.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags = (m.expiresAt ? 1 : 0) | (m.releasedAt ? 2 : 0) | (m.metadata ? 4 : 0)

    c.string.encode(state, m.id)
    c.buffer.encode(state, m.ownerKey)
    c.uint.encode(state, m.acquiredAt)
    c.uint.encode(state, flags)

    if (m.expiresAt) c.uint.encode(state, m.expiresAt)
    if (m.releasedAt) c.uint.encode(state, m.releasedAt)
    c.uint.encode(state, m.rev)
    if (m.metadata) c.string.encode(state, m.metadata)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      ownerKey: r1,
      acquiredAt: r2,
      expiresAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      releasedAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      rev: c.uint.decode(state),
      metadata: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/lock-acquire
const encoding13 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 4 so always one byte

    if (m.acquiredAt) c.uint.preencode(state, m.acquiredAt)
    if (m.expiresAt) c.uint.preencode(state, m.expiresAt)
    if (m.metadata) c.string.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags = (m.acquiredAt ? 1 : 0) | (m.expiresAt ? 2 : 0) | (m.metadata ? 4 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.acquiredAt) c.uint.encode(state, m.acquiredAt)
    if (m.expiresAt) c.uint.encode(state, m.expiresAt)
    if (m.metadata) c.string.encode(state, m.metadata)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      acquiredAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      expiresAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      metadata: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/lock-release
const encoding14 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 1 so always one byte

    if (m.releasedAt) c.uint.preencode(state, m.releasedAt)
  },
  encode(state, m) {
    const flags = m.releasedAt ? 1 : 0

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.releasedAt) c.uint.encode(state, m.releasedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      releasedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonkdocs-doc/metadata
const encoding15 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 8 so always one byte

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    c.uint.preencode(state, m.createdAt)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.creatorKey) c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.rev)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) | (m.description ? 2 : 0) | (m.updatedAt ? 4 : 0) | (m.creatorKey ? 8 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    c.uint.encode(state, m.createdAt)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.creatorKey) c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.rev)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: c.uint.decode(state),
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      creatorKey: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      rev: c.uint.decode(state)
    }
  }
}

// @bonkdocs-doc/metadata-upsert
const encoding16 = encoding15

// @bonkdocs-doc/metadata/hyperdb#0
const encoding17 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    c.uint.preencode(state, m.createdAt)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.creatorKey) c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.rev)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) | (m.description ? 2 : 0) | (m.updatedAt ? 4 : 0) | (m.creatorKey ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    c.uint.encode(state, m.createdAt)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.creatorKey) c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.rev)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: null,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: c.uint.decode(state),
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      creatorKey: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      rev: c.uint.decode(state)
    }
  }
}

// @spaces/writer/hyperdb#1
const encoding18 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      key: null,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @spaces/invite/hyperdb#2.roles
const encoding19_5 = encoding1_5

// @spaces/invite/hyperdb#2
const encoding19 = {
  preencode(state, m) {
    state.end++ // max flag is 64 so always one byte

    if (m.invite) c.buffer.preencode(state, m.invite)
    if (m.publicKey) c.buffer.preencode(state, m.publicKey)
    if (m.secretHash) c.buffer.preencode(state, m.secretHash)
    c.int.preencode(state, m.expires)
    if (m.roles) encoding19_5.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.invite ? 1 : 0) |
      (m.publicKey ? 2 : 0) |
      (m.secretHash ? 4 : 0) |
      (m.roles ? 8 : 0) |
      (m.createdBy ? 16 : 0) |
      (m.createdAt ? 32 : 0) |
      (m.revokedAt ? 64 : 0)

    c.uint.encode(state, flags)

    if (m.invite) c.buffer.encode(state, m.invite)
    if (m.publicKey) c.buffer.encode(state, m.publicKey)
    if (m.secretHash) c.buffer.encode(state, m.secretHash)
    c.int.encode(state, m.expires)
    if (m.roles) encoding19_5.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: null,
      invite: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      publicKey: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      secretHash: (flags & 4) !== 0 ? c.buffer.decode(state) : null,
      expires: c.int.decode(state),
      roles: (flags & 8) !== 0 ? encoding19_5.decode(state) : null,
      createdBy: (flags & 16) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 32) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 64) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @spaces/space-init/hyperdb#3
const encoding20 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.uint.encode(state, m.version)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)

    return {
      creatorKey: null,
      version: r1,
      index: r2,
      timestamp: r3
    }
  }
}

// @spaces/role-def/hyperdb#4.permissions
const encoding21_1 = encoding1_5

// @spaces/role-def/hyperdb#4
const encoding21 = {
  preencode(state, m) {
    encoding21_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    encoding21_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r1 = encoding21_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: null,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @spaces/acl-entry/hyperdb#5.roles
const encoding22_1 = encoding1_5

// @spaces/acl-entry/hyperdb#5
const encoding22 = {
  preencode(state, m) {
    encoding22_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    encoding22_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r1 = encoding22_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: null,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @bonk-docs/yjs-update/hyperdb#6
const encoding23 = {
  preencode(state, m) {
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = m.sessionId ? 1 : 0

    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: 0,
      clientId: r1,
      timestamp: r2,
      data: r3,
      sessionId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-snapshot/hyperdb#7
const encoding24 = {
  preencode(state, m) {
    c.uint.preencode(state, m.createdAt)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags = m.stateVector ? 1 : 0

    c.uint.encode(state, m.createdAt)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: 0,
      createdAt: r1,
      data: r2,
      stateVector: (flags & 1) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-awareness/hyperdb#8
const encoding25 = {
  preencode(state, m) {
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.clientId) c.string.preencode(state, m.clientId)
  },
  encode(state, m) {
    const flags = m.clientId ? 1 : 0

    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.clientId) c.string.encode(state, m.clientId)
  },
  decode(state) {
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: 0,
      timestamp: r1,
      data: r2,
      clientId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/lock/hyperdb#9
const encoding26 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.ownerKey)
    c.uint.preencode(state, m.acquiredAt)
    state.end++ // max flag is 4 so always one byte

    if (m.expiresAt) c.uint.preencode(state, m.expiresAt)
    if (m.releasedAt) c.uint.preencode(state, m.releasedAt)
    c.uint.preencode(state, m.rev)
    if (m.metadata) c.string.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags = (m.expiresAt ? 1 : 0) | (m.releasedAt ? 2 : 0) | (m.metadata ? 4 : 0)

    c.buffer.encode(state, m.ownerKey)
    c.uint.encode(state, m.acquiredAt)
    c.uint.encode(state, flags)

    if (m.expiresAt) c.uint.encode(state, m.expiresAt)
    if (m.releasedAt) c.uint.encode(state, m.releasedAt)
    c.uint.encode(state, m.rev)
    if (m.metadata) c.string.encode(state, m.metadata)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      ownerKey: r1,
      acquiredAt: r2,
      expiresAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      releasedAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      rev: c.uint.decode(state),
      metadata: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@spaces/writer':
      return encoding0
    case '@spaces/invite':
      return encoding1
    case '@spaces/accept-invite':
      return encoding2
    case '@spaces/revoke-invite':
      return encoding3
    case '@spaces/space-init':
      return encoding4
    case '@spaces/role-def':
      return encoding5
    case '@spaces/acl-entry':
      return encoding6
    case '@bonk-docs/yjs-update':
      return encoding7
    case '@bonk-docs/yjs-update-entry':
      return encoding8
    case '@bonk-docs/yjs-snapshot':
      return encoding9
    case '@bonk-docs/yjs-awareness':
      return encoding10
    case '@bonk-docs/yjs-awareness-entry':
      return encoding11
    case '@bonk-docs/lock':
      return encoding12
    case '@bonk-docs/lock-acquire':
      return encoding13
    case '@bonk-docs/lock-release':
      return encoding14
    case '@bonkdocs-doc/metadata':
      return encoding15
    case '@bonkdocs-doc/metadata-upsert':
      return encoding16
    case '@bonkdocs-doc/metadata/hyperdb#0':
      return encoding17
    case '@spaces/writer/hyperdb#1':
      return encoding18
    case '@spaces/invite/hyperdb#2':
      return encoding19
    case '@spaces/space-init/hyperdb#3':
      return encoding20
    case '@spaces/role-def/hyperdb#4':
      return encoding21
    case '@spaces/acl-entry/hyperdb#5':
      return encoding22
    case '@bonk-docs/yjs-update/hyperdb#6':
      return encoding23
    case '@bonk-docs/yjs-snapshot/hyperdb#7':
      return encoding24
    case '@bonk-docs/yjs-awareness/hyperdb#8':
      return encoding25
    case '@bonk-docs/lock/hyperdb#9':
      return encoding26
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
