// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @pear-contracts/upgrade
const encoding0 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
  },
  encode(state, m) {
    c.uint.encode(state, m.version)
  },
  decode(state) {
    const r0 = c.uint.decode(state)

    return {
      version: r0
    }
  }
}

// @spaces/writer
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @spaces/invite.roles
const encoding2_5 = c.array(c.string)

// @spaces/invite
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    state.end++ // max flag is 64 so always one byte

    if (m.invite) c.buffer.preencode(state, m.invite)
    if (m.publicKey) c.buffer.preencode(state, m.publicKey)
    if (m.secretHash) c.buffer.preencode(state, m.secretHash)
    c.int.preencode(state, m.expires)
    if (m.roles) encoding2_5.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.invite ? 1 : 0) |
      (m.publicKey ? 2 : 0) |
      (m.secretHash ? 4 : 0) |
      (m.roles ? 8 : 0) |
      (m.createdBy ? 16 : 0) |
      (m.createdAt ? 32 : 0) |
      (m.revokedAt ? 64 : 0)

    c.buffer.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.invite) c.buffer.encode(state, m.invite)
    if (m.publicKey) c.buffer.encode(state, m.publicKey)
    if (m.secretHash) c.buffer.encode(state, m.secretHash)
    c.int.encode(state, m.expires)
    if (m.roles) encoding2_5.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      publicKey: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      secretHash: (flags & 4) !== 0 ? c.buffer.decode(state) : null,
      expires: c.int.decode(state),
      roles: (flags & 8) !== 0 ? encoding2_5.decode(state) : null,
      createdBy: (flags & 16) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 32) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 64) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @spaces/accept-invite.roles
const encoding3_5 = encoding2_5

// @spaces/accept-invite
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.secret)
    c.uint.preencode(state, m.acceptedAt)
    state.end++ // max flag is 4 so always one byte

    if (m.roles) encoding3_5.preencode(state, m.roles)
  },
  encode(state, m) {
    const flags =
      (m.isIndexer ? 1 : 0) |
      (m.optimistic ? 2 : 0) |
      (m.roles ? 4 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.secret)
    c.uint.encode(state, m.acceptedAt)
    c.uint.encode(state, flags)

    if (m.roles) encoding3_5.encode(state, m.roles)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      secret: r1,
      acceptedAt: r2,
      isIndexer: (flags & 1) !== 0,
      optimistic: (flags & 2) !== 0,
      roles: (flags & 4) !== 0 ? encoding3_5.decode(state) : null
    }
  }
}

// @spaces/revoke-invite
const encoding4 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)

    return {
      id: r0,
      revokedAt: r1
    }
  }
}

// @spaces/space-init
const encoding5 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.version)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.version)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)

    return {
      creatorKey: r0,
      version: r1,
      index: r2,
      timestamp: r3
    }
  }
}

// @spaces/role-def.permissions
const encoding6_1 = encoding2_5

// @spaces/role-def
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    encoding6_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    encoding6_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding6_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: r0,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @spaces/acl-entry.roles
const encoding7_1 = encoding2_5

// @spaces/acl-entry
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.subjectKey)
    encoding7_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.subjectKey)
    encoding7_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding7_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: r0,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @bonk-docs/yjs-update
const encoding8 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = m.sessionId ? 1 : 0

    c.uint.encode(state, m.rev)
    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      clientId: r1,
      timestamp: r2,
      data: r3,
      sessionId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-update-entry
const encoding9 = {
  preencode(state, m) {
    c.string.preencode(state, m.clientId)
    state.end++ // max flag is 2 so always one byte

    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    if (m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags =
      (m.timestamp ? 1 : 0) |
      (m.sessionId ? 2 : 0)

    c.string.encode(state, m.clientId)
    c.uint.encode(state, flags)

    if (m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    if (m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      clientId: r0,
      timestamp: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state),
      sessionId: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-snapshot
const encoding10 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.createdAt)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags = m.stateVector ? 1 : 0

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.createdAt)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      createdAt: r1,
      data: r2,
      stateVector: (flags & 1) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-awareness
const encoding11 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (m.clientId) c.string.preencode(state, m.clientId)
  },
  encode(state, m) {
    const flags = m.clientId ? 1 : 0

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (m.clientId) c.string.encode(state, m.clientId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      timestamp: r1,
      data: r2,
      clientId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/yjs-awareness-entry
const encoding12 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    if (m.clientId) c.string.preencode(state, m.clientId)
  },
  encode(state, m) {
    const flags =
      (m.timestamp ? 1 : 0) |
      (m.clientId ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    if (m.clientId) c.string.encode(state, m.clientId)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      timestamp: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state),
      clientId: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/lock
const encoding13 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.buffer.preencode(state, m.ownerKey)
    c.uint.preencode(state, m.acquiredAt)
    state.end++ // max flag is 4 so always one byte

    if (m.expiresAt) c.uint.preencode(state, m.expiresAt)
    if (m.releasedAt) c.uint.preencode(state, m.releasedAt)
    c.uint.preencode(state, m.rev)
    if (m.metadata) c.string.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags =
      (m.expiresAt ? 1 : 0) |
      (m.releasedAt ? 2 : 0) |
      (m.metadata ? 4 : 0)

    c.string.encode(state, m.id)
    c.buffer.encode(state, m.ownerKey)
    c.uint.encode(state, m.acquiredAt)
    c.uint.encode(state, flags)

    if (m.expiresAt) c.uint.encode(state, m.expiresAt)
    if (m.releasedAt) c.uint.encode(state, m.releasedAt)
    c.uint.encode(state, m.rev)
    if (m.metadata) c.string.encode(state, m.metadata)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      ownerKey: r1,
      acquiredAt: r2,
      expiresAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      releasedAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      rev: c.uint.decode(state),
      metadata: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/lock-acquire
const encoding14 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 4 so always one byte

    if (m.acquiredAt) c.uint.preencode(state, m.acquiredAt)
    if (m.expiresAt) c.uint.preencode(state, m.expiresAt)
    if (m.metadata) c.string.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags =
      (m.acquiredAt ? 1 : 0) |
      (m.expiresAt ? 2 : 0) |
      (m.metadata ? 4 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.acquiredAt) c.uint.encode(state, m.acquiredAt)
    if (m.expiresAt) c.uint.encode(state, m.expiresAt)
    if (m.metadata) c.string.encode(state, m.metadata)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      acquiredAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      expiresAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      metadata: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs/lock-release
const encoding15 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 1 so always one byte

    if (m.releasedAt) c.uint.preencode(state, m.releasedAt)
  },
  encode(state, m) {
    const flags = m.releasedAt ? 1 : 0

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.releasedAt) c.uint.encode(state, m.releasedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      releasedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @pear-data/write
const encoding16 = {
  preencode(state, m) {
    c.string.preencode(state, m.collection)
    c.buffer.preencode(state, m.value)
  },
  encode(state, m) {
    c.string.encode(state, m.collection)
    c.buffer.encode(state, m.value)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      collection: r0,
      value: r1
    }
  }
}

// @pear-data/compare-and-set
const encoding17 = {
  preencode(state, m) {
    c.string.preencode(state, m.collection)
    c.buffer.preencode(state, m.key)
    c.buffer.preencode(state, m.value)
    state.end++ // max flag is 1 so always one byte

    if (m.ifRev) c.uint.preencode(state, m.ifRev)
  },
  encode(state, m) {
    const flags = m.ifRev ? 1 : 0

    c.string.encode(state, m.collection)
    c.buffer.encode(state, m.key)
    c.buffer.encode(state, m.value)
    c.uint.encode(state, flags)

    if (m.ifRev) c.uint.encode(state, m.ifRev)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      collection: r0,
      key: r1,
      value: r2,
      ifRev: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonkdocs-doc/metadata
const encoding18 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 8 so always one byte

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    c.uint.preencode(state, m.createdAt)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.creatorKey) c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.rev)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.updatedAt ? 4 : 0) |
      (m.creatorKey ? 8 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    c.uint.encode(state, m.createdAt)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.creatorKey) c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.rev)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: c.uint.decode(state),
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      creatorKey: (flags & 8) !== 0 ? c.buffer.decode(state) : null,
      rev: c.uint.decode(state)
    }
  }
}

// @pear/contracts
const encoding19 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.uint.preencode(state, m.version)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.uint.encode(state, m.version)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)

    return {
      id: r0,
      version: r1
    }
  }
}

// @bonkdocs-doc/metadata-upsert
const encoding20 = encoding18

// @local/doc
const encoding21 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.encryptionKey)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 64 so always one byte

    if (version >= 2 && m.joinedAt) c.uint.preencode(state, m.joinedAt)
    if (version >= 2 && m.title) c.string.preencode(state, m.title)
    if (version >= 2 && m.lastRevision) c.uint.preencode(state, m.lastRevision)
    if (version >= 2 && m.lastOpenedAt) c.uint.preencode(state, m.lastOpenedAt)
    if (version >= 2 && m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.joinedAt) ? 1 : 0) |
      ((version >= 2 && m.isCreator) ? 2 : 0) |
      ((version >= 2 && m.title) ? 4 : 0) |
      ((version >= 2 && m.lastRevision) ? 8 : 0) |
      ((version >= 2 && m.lastOpenedAt) ? 16 : 0) |
      ((version >= 2 && m.lockedAt) ? 32 : 0) |
      ((version >= 2 && m.lockedBy) ? 64 : 0)

    c.string.encode(state, m.key)
    c.string.encode(state, m.encryptionKey)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (version >= 2 && m.joinedAt) c.uint.encode(state, m.joinedAt)
    if (version >= 2 && m.title) c.string.encode(state, m.title)
    if (version >= 2 && m.lastRevision) c.uint.encode(state, m.lastRevision)
    if (version >= 2 && m.lastOpenedAt) c.uint.encode(state, m.lastOpenedAt)
    if (version >= 2 && m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.encode(state, m.lockedBy)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      encryptionKey: r1,
      createdAt: r2,
      joinedAt: (version >= 2 && (flags & 1) !== 0) ? c.uint.decode(state) : 0,
      isCreator: (version >= 2 && (flags & 2) !== 0),
      title: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      lastRevision: (version >= 2 && (flags & 8) !== 0) ? c.uint.decode(state) : 0,
      lastOpenedAt: (version >= 2 && (flags & 16) !== 0) ? c.uint.decode(state) : 0,
      lockedAt: (version >= 2 && (flags & 32) !== 0) ? c.uint.decode(state) : 0,
      lockedBy: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-capabilities.roles
const encoding22_2 = encoding2_5

// @bonk-docs-rpc/doc-capabilities
const encoding22 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (version >= 2 && m.roles) encoding22_2.preencode(state, m.roles)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.canEdit) ? 1 : 0) |
      ((version >= 2 && m.canInvite) ? 2 : 0) |
      ((version >= 2 && m.roles) ? 4 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.roles) encoding22_2.encode(state, m.roles)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      canEdit: (version >= 2 && (flags & 1) !== 0),
      canInvite: (version >= 2 && (flags & 2) !== 0),
      roles: (version >= 2 && (flags & 4) !== 0) ? encoding22_2.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-update-entry
const encoding23 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 2 && m.rev) c.uint.preencode(state, m.rev)
    c.string.preencode(state, m.clientId)
    if (version >= 2 && m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.rev) ? 1 : 0) |
      ((version >= 2 && m.timestamp) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.rev) c.uint.encode(state, m.rev)
    c.string.encode(state, m.clientId)
    if (version >= 2 && m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      rev: (version >= 2 && (flags & 1) !== 0) ? c.uint.decode(state) : 0,
      clientId: c.string.decode(state),
      timestamp: (version >= 2 && (flags & 2) !== 0) ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state)
    }
  }
}

// @bonk-docs-rpc/doc-update.capabilities
const encoding24_4 = c.frame(encoding22)
// @bonk-docs-rpc/doc-update.updates
const encoding24_8 = c.array(c.frame(encoding23))

// @bonk-docs-rpc/doc-update
const encoding24 = {
  preencode(state, m) {
    const flags =
      ((version >= 2 && m.updatedAt) ? 1 : 0) |
      ((version >= 2 && m.title) ? 2 : 0) |
      ((version >= 2 && m.capabilities) ? 4 : 0) |
      ((version >= 2 && m.lockedAt) ? 8 : 0) |
      ((version >= 2 && m.lockedBy) ? 16 : 0) |
      ((version >= 2 && m.syncUpdate) ? 32 : 0) |
      ((version >= 2 && m.updates) ? 64 : 0) |
      ((version >= 2 && m.awareness) ? 128 : 0) |
      ((version >= 2 && m.writerKey) ? 256 : 0)

    c.string.preencode(state, m.key)
    c.uint.preencode(state, m.revision)
    c.uint.preencode(state, flags)

    if (version >= 2 && m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (version >= 2 && m.title) c.string.preencode(state, m.title)
    if (version >= 2 && m.capabilities) encoding24_4.preencode(state, m.capabilities)
    if (version >= 2 && m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.preencode(state, m.lockedBy)
    if (version >= 2 && m.syncUpdate) c.buffer.preencode(state, m.syncUpdate)
    if (version >= 2 && m.updates) encoding24_8.preencode(state, m.updates)
    if (version >= 2 && m.awareness) c.buffer.preencode(state, m.awareness)
    if (version >= 2 && m.writerKey) c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.updatedAt) ? 1 : 0) |
      ((version >= 2 && m.title) ? 2 : 0) |
      ((version >= 2 && m.capabilities) ? 4 : 0) |
      ((version >= 2 && m.lockedAt) ? 8 : 0) |
      ((version >= 2 && m.lockedBy) ? 16 : 0) |
      ((version >= 2 && m.syncUpdate) ? 32 : 0) |
      ((version >= 2 && m.updates) ? 64 : 0) |
      ((version >= 2 && m.awareness) ? 128 : 0) |
      ((version >= 2 && m.writerKey) ? 256 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, m.revision)
    c.uint.encode(state, flags)

    if (version >= 2 && m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (version >= 2 && m.title) c.string.encode(state, m.title)
    if (version >= 2 && m.capabilities) encoding24_4.encode(state, m.capabilities)
    if (version >= 2 && m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.encode(state, m.lockedBy)
    if (version >= 2 && m.syncUpdate) c.buffer.encode(state, m.syncUpdate)
    if (version >= 2 && m.updates) encoding24_8.encode(state, m.updates)
    if (version >= 2 && m.awareness) c.buffer.encode(state, m.awareness)
    if (version >= 2 && m.writerKey) c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      revision: r1,
      updatedAt: (version >= 2 && (flags & 1) !== 0) ? c.uint.decode(state) : 0,
      title: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      capabilities: (version >= 2 && (flags & 4) !== 0) ? encoding24_4.decode(state) : null,
      lockedAt: (version >= 2 && (flags & 8) !== 0) ? c.uint.decode(state) : 0,
      lockedBy: (version >= 2 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      syncUpdate: (version >= 2 && (flags & 32) !== 0) ? c.buffer.decode(state) : null,
      updates: (version >= 2 && (flags & 64) !== 0) ? encoding24_8.decode(state) : null,
      awareness: (version >= 2 && (flags & 128) !== 0) ? c.buffer.decode(state) : null,
      writerKey: (version >= 2 && (flags & 256) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-invite.roles
const encoding25_2 = encoding2_5

// @bonk-docs-rpc/doc-invite
const encoding25 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 16 so always one byte

    if (version >= 2 && m.roles) encoding25_2.preencode(state, m.roles)
    if (version >= 2 && m.createdBy) c.string.preencode(state, m.createdBy)
    if (version >= 2 && m.createdAt) c.uint.preencode(state, m.createdAt)
    if (version >= 2 && m.revokedAt) c.uint.preencode(state, m.revokedAt)
    if (version >= 2 && m.expiresAt) c.int.preencode(state, m.expiresAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.roles) ? 1 : 0) |
      ((version >= 2 && m.createdBy) ? 2 : 0) |
      ((version >= 2 && m.createdAt) ? 4 : 0) |
      ((version >= 2 && m.revokedAt) ? 8 : 0) |
      ((version >= 2 && m.expiresAt) ? 16 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (version >= 2 && m.roles) encoding25_2.encode(state, m.roles)
    if (version >= 2 && m.createdBy) c.string.encode(state, m.createdBy)
    if (version >= 2 && m.createdAt) c.uint.encode(state, m.createdAt)
    if (version >= 2 && m.revokedAt) c.uint.encode(state, m.revokedAt)
    if (version >= 2 && m.expiresAt) c.int.encode(state, m.expiresAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      roles: (version >= 2 && (flags & 1) !== 0) ? encoding25_2.decode(state) : null,
      createdBy: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      createdAt: (version >= 2 && (flags & 4) !== 0) ? c.uint.decode(state) : 0,
      revokedAt: (version >= 2 && (flags & 8) !== 0) ? c.uint.decode(state) : 0,
      expiresAt: (version >= 2 && (flags & 16) !== 0) ? c.int.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/identity-profile
const encoding26 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (version >= 2 && m.displayName) c.string.preencode(state, m.displayName)
    if (version >= 2 && m.bio) c.string.preencode(state, m.bio)
    if (version >= 2 && m.updatedAt) c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.displayName) ? 1 : 0) |
      ((version >= 2 && m.bio) ? 2 : 0) |
      ((version >= 2 && m.updatedAt) ? 4 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.displayName) c.string.encode(state, m.displayName)
    if (version >= 2 && m.bio) c.string.encode(state, m.bio)
    if (version >= 2 && m.updatedAt) c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      displayName: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      bio: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      updatedAt: (version >= 2 && (flags & 4) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/identity-summary.profile
const encoding27_2 = c.frame(encoding26)

// @bonk-docs-rpc/identity-summary
const encoding27 = {
  preencode(state, m) {
    c.string.preencode(state, m.identityKey)
    c.string.preencode(state, m.writerKey)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.profile) encoding27_2.preencode(state, m.profile)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.profile) ? 1 : 0

    c.string.encode(state, m.identityKey)
    c.string.encode(state, m.writerKey)
    c.uint.encode(state, flags)

    if (version >= 2 && m.profile) encoding27_2.encode(state, m.profile)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      identityKey: r0,
      writerKey: r1,
      profile: (version >= 2 && (flags & 1) !== 0) ? encoding27_2.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/initialize-request
const encoding28 = {
  preencode(state, m) {

  },
  encode(state, m) {

  },
  decode(state) {
    return {
    }
  }
}

// @bonk-docs-rpc/initialize-response.docs
const encoding29_0 = c.array(c.frame(encoding21))
// @bonk-docs-rpc/initialize-response.identity
const encoding29_2 = c.frame(encoding27)

// @bonk-docs-rpc/initialize-response
const encoding29 = {
  preencode(state, m) {
    encoding29_0.preencode(state, m.docs)
    state.end++ // max flag is 2 so always one byte

    if (version >= 2 && m.activeDoc) c.string.preencode(state, m.activeDoc)
    if (version >= 2 && m.identity) encoding29_2.preencode(state, m.identity)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.activeDoc) ? 1 : 0) |
      ((version >= 2 && m.identity) ? 2 : 0)

    encoding29_0.encode(state, m.docs)
    c.uint.encode(state, flags)

    if (version >= 2 && m.activeDoc) c.string.encode(state, m.activeDoc)
    if (version >= 2 && m.identity) encoding29_2.encode(state, m.identity)
  },
  decode(state) {
    const r0 = encoding29_0.decode(state)
    const flags = c.uint.decode(state)

    return {
      docs: r0,
      activeDoc: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      identity: (version >= 2 && (flags & 2) !== 0) ? encoding29_2.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/list-docs-request
const encoding30 = encoding28

// @bonk-docs-rpc/list-docs-response.docs
const encoding31_0 = encoding29_0

// @bonk-docs-rpc/list-docs-response
const encoding31 = {
  preencode(state, m) {
    encoding31_0.preencode(state, m.docs)
  },
  encode(state, m) {
    encoding31_0.encode(state, m.docs)
  },
  decode(state) {
    const r0 = encoding31_0.decode(state)

    return {
      docs: r0
    }
  }
}

// @bonk-docs-rpc/create-doc-request
const encoding32 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.title) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 2 && m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      title: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/create-doc-response.doc
const encoding33_0 = c.frame(encoding21)

// @bonk-docs-rpc/create-doc-response
const encoding33 = {
  preencode(state, m) {
    encoding33_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    encoding33_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = encoding33_0.decode(state)
    const r1 = c.string.decode(state)

    return {
      doc: r0,
      writerKey: r1
    }
  }
}

// @bonk-docs-rpc/join-doc-request
const encoding34 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.title) ? 1 : 0

    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (version >= 2 && m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      invite: r0,
      title: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/join-doc-response.doc
const encoding35_0 = encoding33_0

// @bonk-docs-rpc/join-doc-response
const encoding35 = {
  preencode(state, m) {
    encoding35_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    encoding35_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = encoding35_0.decode(state)
    const r1 = c.string.decode(state)

    return {
      doc: r0,
      writerKey: r1
    }
  }
}

// @bonk-docs-rpc/remove-doc-request
const encoding36 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      key: r0
    }
  }
}

// @bonk-docs-rpc/remove-doc-response
const encoding37 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = (version >= 2 && m.removed) ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      removed: (version >= 2 && (flags & 1) !== 0)
    }
  }
}

// @bonk-docs-rpc/rename-doc-request
const encoding38 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.title) ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (version >= 2 && m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      title: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/rename-doc-response
const encoding39 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.title)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.updatedAt) c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.updatedAt) ? 1 : 0

    c.string.encode(state, m.key)
    c.string.encode(state, m.title)
    c.uint.encode(state, flags)

    if (version >= 2 && m.updatedAt) c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      title: r1,
      updatedAt: (version >= 2 && (flags & 1) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/lock-doc-request
const encoding40 = encoding36

// @bonk-docs-rpc/lock-doc-response
const encoding41 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.uint.preencode(state, m.lockedAt)
    c.string.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.uint.encode(state, m.lockedAt)
    c.string.encode(state, m.lockedBy)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      key: r0,
      lockedAt: r1,
      lockedBy: r2
    }
  }
}

// @bonk-docs-rpc/get-doc-request
const encoding42 = encoding36

// @bonk-docs-rpc/get-doc-response.doc
const encoding43_0 = encoding33_0

// @bonk-docs-rpc/get-doc-response
const encoding43 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 2 && m.doc) encoding43_0.preencode(state, m.doc)
    if (version >= 2 && m.writerKey) c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.doc) ? 1 : 0) |
      ((version >= 2 && m.writerKey) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.doc) encoding43_0.encode(state, m.doc)
    if (version >= 2 && m.writerKey) c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      doc: (version >= 2 && (flags & 1) !== 0) ? encoding43_0.decode(state) : null,
      writerKey: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/watch-doc-request
const encoding44 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.stateVector) ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (version >= 2 && m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      stateVector: (version >= 2 && (flags & 1) !== 0) ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/apply-updates-request.updates
const encoding45_1 = encoding24_8

// @bonk-docs-rpc/apply-updates-request
const encoding45 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    encoding45_1.preencode(state, m.updates)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    encoding45_1.encode(state, m.updates)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding45_1.decode(state)

    return {
      key: r0,
      updates: r1
    }
  }
}

// @bonk-docs-rpc/apply-updates-response
const encoding46 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (version >= 2 && m.revision) c.uint.preencode(state, m.revision)
    if (version >= 2 && m.error) c.string.preencode(state, m.error)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.accepted) ? 1 : 0) |
      ((version >= 2 && m.revision) ? 2 : 0) |
      ((version >= 2 && m.error) ? 4 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.revision) c.uint.encode(state, m.revision)
    if (version >= 2 && m.error) c.string.encode(state, m.error)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      accepted: (version >= 2 && (flags & 1) !== 0),
      revision: (version >= 2 && (flags & 2) !== 0) ? c.uint.decode(state) : 0,
      error: (version >= 2 && (flags & 4) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/apply-awareness-request
const encoding47 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.buffer.preencode(state, m.update)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.buffer.encode(state, m.update)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      key: r0,
      update: r1
    }
  }
}

// @bonk-docs-rpc/apply-awareness-response
const encoding48 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = (version >= 2 && m.accepted) ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      accepted: (version >= 2 && (flags & 1) !== 0)
    }
  }
}

// @bonk-docs-rpc/list-invites-request
const encoding49 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = (version >= 2 && m.includeRevoked) ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      includeRevoked: (version >= 2 && (flags & 1) !== 0)
    }
  }
}

// @bonk-docs-rpc/list-invites-response.invites
const encoding50_0 = c.array(c.frame(encoding25))

// @bonk-docs-rpc/list-invites-response
const encoding50 = {
  preencode(state, m) {
    encoding50_0.preencode(state, m.invites)
  },
  encode(state, m) {
    encoding50_0.encode(state, m.invites)
  },
  decode(state) {
    const r0 = encoding50_0.decode(state)

    return {
      invites: r0
    }
  }
}

// @bonk-docs-rpc/create-invite-request.roles
const encoding51_1 = encoding2_5

// @bonk-docs-rpc/create-invite-request
const encoding51 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 2 so always one byte

    if (version >= 2 && m.roles) encoding51_1.preencode(state, m.roles)
    if (version >= 2 && m.expiresAt) c.uint.preencode(state, m.expiresAt)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.roles) ? 1 : 0) |
      ((version >= 2 && m.expiresAt) ? 2 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (version >= 2 && m.roles) encoding51_1.encode(state, m.roles)
    if (version >= 2 && m.expiresAt) c.uint.encode(state, m.expiresAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      roles: (version >= 2 && (flags & 1) !== 0) ? encoding51_1.decode(state) : null,
      expiresAt: (version >= 2 && (flags & 2) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/create-invite-response
const encoding52 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
    c.string.preencode(state, m.inviteId)
  },
  encode(state, m) {
    c.string.encode(state, m.invite)
    c.string.encode(state, m.inviteId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      invite: r0,
      inviteId: r1
    }
  }
}

// @bonk-docs-rpc/revoke-invite-request
const encoding53 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.inviteId)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.string.encode(state, m.inviteId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      key: r0,
      inviteId: r1
    }
  }
}

// @bonk-docs-rpc/revoke-invite-response
const encoding54 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = (version >= 2 && m.revoked) ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      revoked: (version >= 2 && (flags & 1) !== 0)
    }
  }
}

// @bonk-docs-rpc/pair-invite-request
const encoding55 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
  },
  encode(state, m) {
    c.string.encode(state, m.invite)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      invite: r0
    }
  }
}

// @bonk-docs-rpc/pair-status.doc
const encoding56_3 = encoding33_0

// @bonk-docs-rpc/pair-status
const encoding56 = {
  preencode(state, m) {
    c.string.preencode(state, m.state)
    state.end++ // max flag is 8 so always one byte

    if (version >= 2 && m.message) c.string.preencode(state, m.message)
    if (version >= 2 && m.progress) c.uint.preencode(state, m.progress)
    if (version >= 2 && m.doc) encoding56_3.preencode(state, m.doc)
    if (version >= 2 && m.writerKey) c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.message) ? 1 : 0) |
      ((version >= 2 && m.progress) ? 2 : 0) |
      ((version >= 2 && m.doc) ? 4 : 0) |
      ((version >= 2 && m.writerKey) ? 8 : 0)

    c.string.encode(state, m.state)
    c.uint.encode(state, flags)

    if (version >= 2 && m.message) c.string.encode(state, m.message)
    if (version >= 2 && m.progress) c.uint.encode(state, m.progress)
    if (version >= 2 && m.doc) encoding56_3.encode(state, m.doc)
    if (version >= 2 && m.writerKey) c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      state: r0,
      message: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      progress: (version >= 2 && (flags & 2) !== 0) ? c.uint.decode(state) : 0,
      doc: (version >= 2 && (flags & 4) !== 0) ? encoding56_3.decode(state) : null,
      writerKey: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@pear-contracts/upgrade':
      return encoding0
    case '@spaces/writer':
      return encoding1
    case '@spaces/invite':
      return encoding2
    case '@spaces/accept-invite':
      return encoding3
    case '@spaces/revoke-invite':
      return encoding4
    case '@spaces/space-init':
      return encoding5
    case '@spaces/role-def':
      return encoding6
    case '@spaces/acl-entry':
      return encoding7
    case '@bonk-docs/yjs-update':
      return encoding8
    case '@bonk-docs/yjs-update-entry':
      return encoding9
    case '@bonk-docs/yjs-snapshot':
      return encoding10
    case '@bonk-docs/yjs-awareness':
      return encoding11
    case '@bonk-docs/yjs-awareness-entry':
      return encoding12
    case '@bonk-docs/lock':
      return encoding13
    case '@bonk-docs/lock-acquire':
      return encoding14
    case '@bonk-docs/lock-release':
      return encoding15
    case '@pear-data/write':
      return encoding16
    case '@pear-data/compare-and-set':
      return encoding17
    case '@bonkdocs-doc/metadata':
      return encoding18
    case '@pear/contracts':
      return encoding19
    case '@bonkdocs-doc/metadata-upsert':
      return encoding20
    case '@local/doc':
      return encoding21
    case '@bonk-docs-rpc/doc-capabilities':
      return encoding22
    case '@bonk-docs-rpc/doc-update-entry':
      return encoding23
    case '@bonk-docs-rpc/doc-update':
      return encoding24
    case '@bonk-docs-rpc/doc-invite':
      return encoding25
    case '@bonk-docs-rpc/identity-profile':
      return encoding26
    case '@bonk-docs-rpc/identity-summary':
      return encoding27
    case '@bonk-docs-rpc/initialize-request':
      return encoding28
    case '@bonk-docs-rpc/initialize-response':
      return encoding29
    case '@bonk-docs-rpc/list-docs-request':
      return encoding30
    case '@bonk-docs-rpc/list-docs-response':
      return encoding31
    case '@bonk-docs-rpc/create-doc-request':
      return encoding32
    case '@bonk-docs-rpc/create-doc-response':
      return encoding33
    case '@bonk-docs-rpc/join-doc-request':
      return encoding34
    case '@bonk-docs-rpc/join-doc-response':
      return encoding35
    case '@bonk-docs-rpc/remove-doc-request':
      return encoding36
    case '@bonk-docs-rpc/remove-doc-response':
      return encoding37
    case '@bonk-docs-rpc/rename-doc-request':
      return encoding38
    case '@bonk-docs-rpc/rename-doc-response':
      return encoding39
    case '@bonk-docs-rpc/lock-doc-request':
      return encoding40
    case '@bonk-docs-rpc/lock-doc-response':
      return encoding41
    case '@bonk-docs-rpc/get-doc-request':
      return encoding42
    case '@bonk-docs-rpc/get-doc-response':
      return encoding43
    case '@bonk-docs-rpc/watch-doc-request':
      return encoding44
    case '@bonk-docs-rpc/apply-updates-request':
      return encoding45
    case '@bonk-docs-rpc/apply-updates-response':
      return encoding46
    case '@bonk-docs-rpc/apply-awareness-request':
      return encoding47
    case '@bonk-docs-rpc/apply-awareness-response':
      return encoding48
    case '@bonk-docs-rpc/list-invites-request':
      return encoding49
    case '@bonk-docs-rpc/list-invites-response':
      return encoding50
    case '@bonk-docs-rpc/create-invite-request':
      return encoding51
    case '@bonk-docs-rpc/create-invite-response':
      return encoding52
    case '@bonk-docs-rpc/revoke-invite-request':
      return encoding53
    case '@bonk-docs-rpc/revoke-invite-response':
      return encoding54
    case '@bonk-docs-rpc/pair-invite-request':
      return encoding55
    case '@bonk-docs-rpc/pair-status':
      return encoding56
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
