// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobonk/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @autobonk/invite.roles
const encoding1_4 = c.array(c.string)

// @autobonk/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
    state.end++ // max flag is 8 so always one byte

    if (m.roles) encoding1_4.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.createdBy ? 2 : 0) |
      (m.createdAt ? 4 : 0) |
      (m.revokedAt ? 8 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.roles) encoding1_4.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3,
      roles: (flags & 1) !== 0 ? encoding1_4.decode(state) : null,
      createdBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @autobonk/revoke-invite
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)

    return {
      id: r0,
      revokedAt: r1
    }
  }
}

// @autobonk/context-init
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)

    return {
      creatorKey: r0,
      index: r1,
      timestamp: r2
    }
  }
}

// @autobonk/role-def.permissions
const encoding4_1 = encoding1_4

// @autobonk/role-def
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    encoding4_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    encoding4_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding4_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: r0,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @autobonk/acl-entry.roles
const encoding5_1 = encoding1_4

// @autobonk/acl-entry
const encoding5 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.subjectKey)
    encoding5_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.subjectKey)
    encoding5_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding5_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: r0,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @local/doc
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.encryptionKey)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 2 so always one byte

    if (m.joinedAt) c.uint.preencode(state, m.joinedAt)
  },
  encode(state, m) {
    const flags =
      (m.joinedAt ? 1 : 0) |
      (m.isCreator ? 2 : 0)

    c.string.encode(state, m.key)
    c.string.encode(state, m.encryptionKey)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.joinedAt) c.uint.encode(state, m.joinedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      encryptionKey: r1,
      createdAt: r2,
      joinedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      isCreator: (flags & 2) !== 0
    }
  }
}

// @pear-docs-rpc/initialize-request
const encoding7 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.refresh ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      refresh: (flags & 1) !== 0
    }
  }
}

// @pear-docs-rpc/initialize-response.docs
const encoding8_0 = c.array(c.frame(encoding6))

// @pear-docs-rpc/initialize-response
const encoding8 = {
  preencode(state, m) {
    encoding8_0.preencode(state, m.docs)
    state.end++ // max flag is 1 so always one byte

    if (m.activeDoc) c.string.preencode(state, m.activeDoc)
  },
  encode(state, m) {
    const flags = m.activeDoc ? 1 : 0

    encoding8_0.encode(state, m.docs)
    c.uint.encode(state, flags)

    if (m.activeDoc) c.string.encode(state, m.activeDoc)
  },
  decode(state) {
    const r0 = encoding8_0.decode(state)
    const flags = c.uint.decode(state)

    return {
      docs: r0,
      activeDoc: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @pear-docs-rpc/list-docs-request
const encoding9 = encoding7

// @pear-docs-rpc/list-docs-response.docs
const encoding10_0 = encoding8_0

// @pear-docs-rpc/list-docs-response
const encoding10 = {
  preencode(state, m) {
    encoding10_0.preencode(state, m.docs)
  },
  encode(state, m) {
    encoding10_0.encode(state, m.docs)
  },
  decode(state) {
    const r0 = encoding10_0.decode(state)

    return {
      docs: r0
    }
  }
}

// @pear-docs-rpc/create-doc-request
const encoding11 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.name) c.string.preencode(state, m.name)
    if (m.displayName) c.string.preencode(state, m.displayName)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.displayName ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.displayName) c.string.encode(state, m.displayName)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      displayName: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @pear-docs-rpc/create-doc-response.doc
const encoding12_0 = c.frame(encoding6)

// @pear-docs-rpc/create-doc-response
const encoding12 = {
  preencode(state, m) {
    encoding12_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
    state.end++ // max flag is 1 so always one byte

    if (m.invite) c.string.preencode(state, m.invite)
  },
  encode(state, m) {
    const flags = m.invite ? 1 : 0

    encoding12_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
    c.uint.encode(state, flags)

    if (m.invite) c.string.encode(state, m.invite)
  },
  decode(state) {
    const r0 = encoding12_0.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      doc: r0,
      writerKey: r1,
      invite: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @pear-docs-rpc/join-doc-request
const encoding13 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 2 so always one byte

    if (m.name) c.string.preencode(state, m.name)
    if (m.displayName) c.string.preencode(state, m.displayName)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.displayName ? 2 : 0)

    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.displayName) c.string.encode(state, m.displayName)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      invite: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      displayName: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @pear-docs-rpc/join-doc-response.doc
const encoding14_0 = encoding12_0

// @pear-docs-rpc/join-doc-response
const encoding14 = {
  preencode(state, m) {
    encoding14_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    encoding14_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = encoding14_0.decode(state)
    const r1 = c.string.decode(state)

    return {
      doc: r0,
      writerKey: r1
    }
  }
}

// @pear-docs-rpc/remove-doc-request
const encoding15 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      key: r0
    }
  }
}

// @pear-docs-rpc/remove-doc-response
const encoding16 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.removed ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      removed: (flags & 1) !== 0
    }
  }
}

// @pear-docs-rpc/get-doc-request
const encoding17 = encoding15

// @pear-docs-rpc/get-doc-response.doc
const encoding18_0 = encoding12_0

// @pear-docs-rpc/get-doc-response
const encoding18 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.doc) encoding18_0.preencode(state, m.doc)
  },
  encode(state, m) {
    const flags = m.doc ? 1 : 0

    c.uint.encode(state, flags)

    if (m.doc) encoding18_0.encode(state, m.doc)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      doc: (flags & 1) !== 0 ? encoding18_0.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autobonk/writer':
      return encoding0
    case '@autobonk/invite':
      return encoding1
    case '@autobonk/revoke-invite':
      return encoding2
    case '@autobonk/context-init':
      return encoding3
    case '@autobonk/role-def':
      return encoding4
    case '@autobonk/acl-entry':
      return encoding5
    case '@local/doc':
      return encoding6
    case '@pear-docs-rpc/initialize-request':
      return encoding7
    case '@pear-docs-rpc/initialize-response':
      return encoding8
    case '@pear-docs-rpc/list-docs-request':
      return encoding9
    case '@pear-docs-rpc/list-docs-response':
      return encoding10
    case '@pear-docs-rpc/create-doc-request':
      return encoding11
    case '@pear-docs-rpc/create-doc-response':
      return encoding12
    case '@pear-docs-rpc/join-doc-request':
      return encoding13
    case '@pear-docs-rpc/join-doc-response':
      return encoding14
    case '@pear-docs-rpc/remove-doc-request':
      return encoding15
    case '@pear-docs-rpc/remove-doc-response':
      return encoding16
    case '@pear-docs-rpc/get-doc-request':
      return encoding17
    case '@pear-docs-rpc/get-doc-response':
      return encoding18
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
