// This file is autogenerated by the hyperschema compiler
// Schema Version: 5
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 5

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobonk/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @autobonk/invite.roles
const encoding1_4 = c.array(c.string)

// @autobonk/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
    state.end++ // max flag is 8 so always one byte

    if (m.roles) encoding1_4.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.createdBy ? 2 : 0) |
      (m.createdAt ? 4 : 0) |
      (m.revokedAt ? 8 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.roles) encoding1_4.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3,
      roles: (flags & 1) !== 0 ? encoding1_4.decode(state) : null,
      createdBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @autobonk/revoke-invite
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)

    return {
      id: r0,
      revokedAt: r1
    }
  }
}

// @autobonk/context-init
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)

    return {
      creatorKey: r0,
      index: r1,
      timestamp: r2
    }
  }
}

// @autobonk/role-def.permissions
const encoding4_1 = encoding1_4

// @autobonk/role-def
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    encoding4_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    encoding4_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding4_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: r0,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @autobonk/acl-entry.roles
const encoding5_1 = encoding1_4

// @autobonk/acl-entry
const encoding5 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.subjectKey)
    encoding5_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.subjectKey)
    encoding5_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding5_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: r0,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @bonk-docs/metadata
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 32 so always one byte

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    c.uint.preencode(state, m.createdAt)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.creatorKey) c.fixed32.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.rev)
    if (version >= 2 && m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.fixed32.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.updatedAt ? 4 : 0) |
      (m.creatorKey ? 8 : 0) |
      ((version >= 2 && m.lockedAt) ? 16 : 0) |
      ((version >= 2 && m.lockedBy) ? 32 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    c.uint.encode(state, m.createdAt)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.creatorKey) c.fixed32.encode(state, m.creatorKey)
    c.uint.encode(state, m.rev)
    if (version >= 2 && m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.fixed32.encode(state, m.lockedBy)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: c.uint.decode(state),
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      creatorKey: (flags & 8) !== 0 ? c.fixed32.decode(state) : null,
      rev: c.uint.decode(state),
      lockedAt: (version >= 2 && (flags & 16) !== 0) ? c.uint.decode(state) : 0,
      lockedBy: (version >= 2 && (flags & 32) !== 0) ? c.fixed32.decode(state) : null
    }
  }
}

// @bonk-docs/operation
const encoding7 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.baseRev)
    c.fixed32.preencode(state, m.clientId)
    state.end++ // max flag is 1 so always one byte

    if (m.sessionId) c.fixed32.preencode(state, m.sessionId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    const flags = m.sessionId ? 1 : 0

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.baseRev)
    c.fixed32.encode(state, m.clientId)
    c.uint.encode(state, flags)

    if (m.sessionId) c.fixed32.encode(state, m.sessionId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.fixed32.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      baseRev: r1,
      clientId: r2,
      sessionId: (flags & 1) !== 0 ? c.fixed32.decode(state) : null,
      timestamp: c.uint.decode(state),
      data: c.buffer.decode(state)
    }
  }
}

// @bonk-docs/snapshot
const encoding8 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 4 so always one byte

    if (m.compression) c.string.preencode(state, m.compression)
    c.buffer.preencode(state, m.data)
    if (m.hash) c.buffer.preencode(state, m.hash)
    if (version >= 3 && m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags =
      (m.compression ? 1 : 0) |
      (m.hash ? 2 : 0) |
      ((version >= 3 && m.stateVector) ? 4 : 0)

    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.compression) c.string.encode(state, m.compression)
    c.buffer.encode(state, m.data)
    if (m.hash) c.buffer.encode(state, m.hash)
    if (version >= 3 && m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: r0,
      createdAt: r1,
      compression: (flags & 1) !== 0 ? c.string.decode(state) : null,
      data: c.buffer.decode(state),
      hash: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      stateVector: (version >= 3 && (flags & 4) !== 0) ? c.buffer.decode(state) : null
    }
  }
}

// @local/doc
const encoding9 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.encryptionKey)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 64 so always one byte

    if (m.joinedAt) c.uint.preencode(state, m.joinedAt)
    if (m.title) c.string.preencode(state, m.title)
    if (m.lastRevision) c.uint.preencode(state, m.lastRevision)
    if (m.lastOpenedAt) c.uint.preencode(state, m.lastOpenedAt)
    if (version >= 2 && m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    const flags =
      (m.joinedAt ? 1 : 0) |
      (m.isCreator ? 2 : 0) |
      (m.title ? 4 : 0) |
      (m.lastRevision ? 8 : 0) |
      (m.lastOpenedAt ? 16 : 0) |
      ((version >= 2 && m.lockedAt) ? 32 : 0) |
      ((version >= 2 && m.lockedBy) ? 64 : 0)

    c.string.encode(state, m.key)
    c.string.encode(state, m.encryptionKey)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.joinedAt) c.uint.encode(state, m.joinedAt)
    if (m.title) c.string.encode(state, m.title)
    if (m.lastRevision) c.uint.encode(state, m.lastRevision)
    if (m.lastOpenedAt) c.uint.encode(state, m.lastOpenedAt)
    if (version >= 2 && m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.encode(state, m.lockedBy)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      encryptionKey: r1,
      createdAt: r2,
      joinedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      isCreator: (flags & 2) !== 0,
      title: (flags & 4) !== 0 ? c.string.decode(state) : null,
      lastRevision: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      lastOpenedAt: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      lockedAt: (version >= 2 && (flags & 32) !== 0) ? c.uint.decode(state) : 0,
      lockedBy: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @local/state
const encoding10 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 2 so always one byte

    if (m.activeDoc) c.string.preencode(state, m.activeDoc)
    if (m.lastSeenAt) c.uint.preencode(state, m.lastSeenAt)
  },
  encode(state, m) {
    const flags =
      (m.activeDoc ? 1 : 0) |
      (m.lastSeenAt ? 2 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.activeDoc) c.string.encode(state, m.activeDoc)
    if (m.lastSeenAt) c.uint.encode(state, m.lastSeenAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      activeDoc: (flags & 1) !== 0 ? c.string.decode(state) : null,
      lastSeenAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @local/profile
const encoding11 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 4 so always one byte

    if (m.displayName) c.string.preencode(state, m.displayName)
    if (m.color) c.string.preencode(state, m.color)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.displayName ? 1 : 0) |
      (m.color ? 2 : 0) |
      (m.updatedAt ? 4 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.displayName) c.string.encode(state, m.displayName)
    if (m.color) c.string.encode(state, m.color)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      displayName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      color: (flags & 2) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/doc-capabilities.roles
const encoding12_3 = encoding1_4

// @bonk-docs-rpc/doc-capabilities
const encoding12 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.roles) encoding12_3.preencode(state, m.roles)
  },
  encode(state, m) {
    const flags =
      (m.canEdit ? 1 : 0) |
      (m.canComment ? 2 : 0) |
      (m.canInvite ? 4 : 0) |
      (m.roles ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.roles) encoding12_3.encode(state, m.roles)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      canEdit: (flags & 1) !== 0,
      canComment: (flags & 2) !== 0,
      canInvite: (flags & 4) !== 0,
      roles: (flags & 8) !== 0 ? encoding12_3.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-operation
const encoding13 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.rev) c.uint.preencode(state, m.rev)
    if (m.baseRev) c.uint.preencode(state, m.baseRev)
    c.string.preencode(state, m.clientId)
    if (m.sessionId) c.string.preencode(state, m.sessionId)
    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    const flags =
      (m.rev ? 1 : 0) |
      (m.baseRev ? 2 : 0) |
      (m.sessionId ? 4 : 0) |
      (m.timestamp ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.rev) c.uint.encode(state, m.rev)
    if (m.baseRev) c.uint.encode(state, m.baseRev)
    c.string.encode(state, m.clientId)
    if (m.sessionId) c.string.encode(state, m.sessionId)
    if (m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      rev: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      baseRev: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      clientId: c.string.decode(state),
      sessionId: (flags & 4) !== 0 ? c.string.decode(state) : null,
      timestamp: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state)
    }
  }
}

// @bonk-docs-rpc/doc-update.ops
const encoding14_7 = c.array(c.frame(encoding13))
// @bonk-docs-rpc/doc-update.capabilities
const encoding14_8 = c.frame(encoding12)

// @bonk-docs-rpc/doc-update
const encoding14 = {
  preencode(state, m) {
    const flags =
      (m.baseRevision ? 1 : 0) |
      (m.snapshotRevision ? 2 : 0) |
      (m.updatedAt ? 4 : 0) |
      (m.title ? 8 : 0) |
      (m.snapshot ? 16 : 0) |
      (m.ops ? 32 : 0) |
      (m.capabilities ? 64 : 0) |
      ((version >= 2 && m.lockedAt) ? 128 : 0) |
      ((version >= 2 && m.lockedBy) ? 256 : 0) |
      ((version >= 3 && m.syncUpdate) ? 512 : 0) |
      ((version >= 3 && m.updates) ? 1024 : 0) |
      ((version >= 3 && m.awareness) ? 2048 : 0)

    c.string.preencode(state, m.key)
    c.uint.preencode(state, m.revision)
    c.uint.preencode(state, flags)

    if (m.baseRevision) c.uint.preencode(state, m.baseRevision)
    if (m.snapshotRevision) c.uint.preencode(state, m.snapshotRevision)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.title) c.string.preencode(state, m.title)
    if (m.snapshot) c.buffer.preencode(state, m.snapshot)
    if (m.ops) encoding14_7.preencode(state, m.ops)
    if (m.capabilities) encoding14_8.preencode(state, m.capabilities)
    if (version >= 2 && m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.preencode(state, m.lockedBy)
    if (version >= 3 && m.syncUpdate) c.buffer.preencode(state, m.syncUpdate)
    if (version >= 3 && m.updates) encoding14_12.preencode(state, m.updates)
    if (version >= 3 && m.awareness) c.buffer.preencode(state, m.awareness)
  },
  encode(state, m) {
    const flags =
      (m.baseRevision ? 1 : 0) |
      (m.snapshotRevision ? 2 : 0) |
      (m.updatedAt ? 4 : 0) |
      (m.title ? 8 : 0) |
      (m.snapshot ? 16 : 0) |
      (m.ops ? 32 : 0) |
      (m.capabilities ? 64 : 0) |
      ((version >= 2 && m.lockedAt) ? 128 : 0) |
      ((version >= 2 && m.lockedBy) ? 256 : 0) |
      ((version >= 3 && m.syncUpdate) ? 512 : 0) |
      ((version >= 3 && m.updates) ? 1024 : 0) |
      ((version >= 3 && m.awareness) ? 2048 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, m.revision)
    c.uint.encode(state, flags)

    if (m.baseRevision) c.uint.encode(state, m.baseRevision)
    if (m.snapshotRevision) c.uint.encode(state, m.snapshotRevision)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.title) c.string.encode(state, m.title)
    if (m.snapshot) c.buffer.encode(state, m.snapshot)
    if (m.ops) encoding14_7.encode(state, m.ops)
    if (m.capabilities) encoding14_8.encode(state, m.capabilities)
    if (version >= 2 && m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.encode(state, m.lockedBy)
    if (version >= 3 && m.syncUpdate) c.buffer.encode(state, m.syncUpdate)
    if (version >= 3 && m.updates) encoding14_12.encode(state, m.updates)
    if (version >= 3 && m.awareness) c.buffer.encode(state, m.awareness)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      revision: r1,
      baseRevision: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      snapshotRevision: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      title: (flags & 8) !== 0 ? c.string.decode(state) : null,
      snapshot: (flags & 16) !== 0 ? c.buffer.decode(state) : null,
      ops: (flags & 32) !== 0 ? encoding14_7.decode(state) : null,
      capabilities: (flags & 64) !== 0 ? encoding14_8.decode(state) : null,
      lockedAt: (version >= 2 && (flags & 128) !== 0) ? c.uint.decode(state) : 0,
      lockedBy: (version >= 2 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      syncUpdate: (version >= 3 && (flags & 512) !== 0) ? c.buffer.decode(state) : null,
      updates: (version >= 3 && (flags & 1024) !== 0) ? encoding14_12.decode(state) : null,
      awareness: (version >= 3 && (flags & 2048) !== 0) ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-invite.roles
const encoding15_2 = encoding1_4

// @bonk-docs-rpc/doc-invite
const encoding15 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 16 so always one byte

    if (m.roles) encoding15_2.preencode(state, m.roles)
    if (m.createdBy) c.string.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
    if (m.expiresAt) c.int.preencode(state, m.expiresAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.createdBy ? 2 : 0) |
      (m.createdAt ? 4 : 0) |
      (m.revokedAt ? 8 : 0) |
      (m.expiresAt ? 16 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (m.roles) encoding15_2.encode(state, m.roles)
    if (m.createdBy) c.string.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
    if (m.expiresAt) c.int.encode(state, m.expiresAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      roles: (flags & 1) !== 0 ? encoding15_2.decode(state) : null,
      createdBy: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      expiresAt: (flags & 16) !== 0 ? c.int.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/initialize-request
const encoding16 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.refresh ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      refresh: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/initialize-response.docs
const encoding17_0 = c.array(c.frame(encoding9))

// @bonk-docs-rpc/initialize-response
const encoding17 = {
  preencode(state, m) {
    encoding17_0.preencode(state, m.docs)
    state.end++ // max flag is 1 so always one byte

    if (m.activeDoc) c.string.preencode(state, m.activeDoc)
  },
  encode(state, m) {
    const flags = m.activeDoc ? 1 : 0

    encoding17_0.encode(state, m.docs)
    c.uint.encode(state, flags)

    if (m.activeDoc) c.string.encode(state, m.activeDoc)
  },
  decode(state) {
    const r0 = encoding17_0.decode(state)
    const flags = c.uint.decode(state)

    return {
      docs: r0,
      activeDoc: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/list-docs-request
const encoding18 = encoding16

// @bonk-docs-rpc/list-docs-response.docs
const encoding19_0 = encoding17_0

// @bonk-docs-rpc/list-docs-response
const encoding19 = {
  preencode(state, m) {
    encoding19_0.preencode(state, m.docs)
  },
  encode(state, m) {
    encoding19_0.encode(state, m.docs)
  },
  decode(state) {
    const r0 = encoding19_0.decode(state)

    return {
      docs: r0
    }
  }
}

// @bonk-docs-rpc/create-doc-request
const encoding20 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.title) c.string.preencode(state, m.title)
    if (m.displayName) c.string.preencode(state, m.displayName)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.displayName ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.displayName) c.string.encode(state, m.displayName)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      displayName: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/create-doc-response.doc
const encoding21_0 = c.frame(encoding9)

// @bonk-docs-rpc/create-doc-response
const encoding21 = {
  preencode(state, m) {
    encoding21_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
    state.end++ // max flag is 1 so always one byte

    if (m.invite) c.string.preencode(state, m.invite)
  },
  encode(state, m) {
    const flags = m.invite ? 1 : 0

    encoding21_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
    c.uint.encode(state, flags)

    if (m.invite) c.string.encode(state, m.invite)
  },
  decode(state) {
    const r0 = encoding21_0.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      doc: r0,
      writerKey: r1,
      invite: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/join-doc-request
const encoding22 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 1 so always one byte

    if (m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = m.title ? 1 : 0

    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      invite: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/join-doc-response.doc
const encoding23_0 = encoding21_0

// @bonk-docs-rpc/join-doc-response
const encoding23 = {
  preencode(state, m) {
    encoding23_0.preencode(state, m.doc)
    c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    encoding23_0.encode(state, m.doc)
    c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = encoding23_0.decode(state)
    const r1 = c.string.decode(state)

    return {
      doc: r0,
      writerKey: r1
    }
  }
}

// @bonk-docs-rpc/remove-doc-request
const encoding24 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      key: r0
    }
  }
}

// @bonk-docs-rpc/remove-doc-response
const encoding25 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.removed ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      removed: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/rename-doc-request
const encoding26 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (m.title) c.string.preencode(state, m.title)
  },
  encode(state, m) {
    const flags = m.title ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/rename-doc-response
const encoding27 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.title)
    state.end++ // max flag is 2 so always one byte

    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.rev) c.uint.preencode(state, m.rev)
  },
  encode(state, m) {
    const flags =
      (m.updatedAt ? 1 : 0) |
      (m.rev ? 2 : 0)

    c.string.encode(state, m.key)
    c.string.encode(state, m.title)
    c.uint.encode(state, flags)

    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.rev) c.uint.encode(state, m.rev)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      title: r1,
      updatedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      rev: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/get-doc-request
const encoding28 = encoding24

// @bonk-docs-rpc/get-doc-response.doc
const encoding29_0 = encoding21_0

// @bonk-docs-rpc/get-doc-response
const encoding29 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.doc) encoding29_0.preencode(state, m.doc)
  },
  encode(state, m) {
    const flags = m.doc ? 1 : 0

    c.uint.encode(state, flags)

    if (m.doc) encoding29_0.encode(state, m.doc)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      doc: (flags & 1) !== 0 ? encoding29_0.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/watch-doc-request
const encoding30 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 4 so always one byte

    if (m.sinceRevision) c.uint.preencode(state, m.sinceRevision)
    if (version >= 3 && m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags =
      (m.sinceRevision ? 1 : 0) |
      (m.includeSnapshot ? 2 : 0) |
      ((version >= 3 && m.stateVector) ? 4 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.sinceRevision) c.uint.encode(state, m.sinceRevision)
    if (version >= 3 && m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      sinceRevision: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      includeSnapshot: (flags & 2) !== 0,
      stateVector: (version >= 3 && (flags & 4) !== 0) ? c.buffer.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/apply-ops-request.ops
const encoding31_1 = encoding14_7

// @bonk-docs-rpc/apply-ops-request
const encoding31 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    encoding31_1.preencode(state, m.ops)
    state.end++ // max flag is 1 so always one byte

    if (m.clientTime) c.uint.preencode(state, m.clientTime)
  },
  encode(state, m) {
    const flags = m.clientTime ? 1 : 0

    c.string.encode(state, m.key)
    encoding31_1.encode(state, m.ops)
    c.uint.encode(state, flags)

    if (m.clientTime) c.uint.encode(state, m.clientTime)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding31_1.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      ops: r1,
      clientTime: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/apply-ops-response
const encoding32 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.revision) c.uint.preencode(state, m.revision)
    if (m.error) c.string.preencode(state, m.error)
  },
  encode(state, m) {
    const flags =
      (m.accepted ? 1 : 0) |
      (m.revision ? 2 : 0) |
      (m.error ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.revision) c.uint.encode(state, m.revision)
    if (m.error) c.string.encode(state, m.error)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      accepted: (flags & 1) !== 0,
      revision: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      error: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/update-presence-request
const encoding33 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.sessionId)
    state.end++ // max flag is 8 so always one byte

    if (m.displayName) c.string.preencode(state, m.displayName)
    if (m.color) c.string.preencode(state, m.color)
    if (m.payload) c.buffer.preencode(state, m.payload)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.displayName ? 1 : 0) |
      (m.color ? 2 : 0) |
      (m.payload ? 4 : 0) |
      (m.updatedAt ? 8 : 0)

    c.string.encode(state, m.key)
    c.string.encode(state, m.sessionId)
    c.uint.encode(state, flags)

    if (m.displayName) c.string.encode(state, m.displayName)
    if (m.color) c.string.encode(state, m.color)
    if (m.payload) c.buffer.encode(state, m.payload)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      sessionId: r1,
      displayName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      color: (flags & 2) !== 0 ? c.string.decode(state) : null,
      payload: (flags & 4) !== 0 ? c.buffer.decode(state) : null,
      updatedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/update-presence-response
const encoding34 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.status) c.string.preencode(state, m.status)
  },
  encode(state, m) {
    const flags = m.status ? 1 : 0

    c.uint.encode(state, flags)

    if (m.status) c.string.encode(state, m.status)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      status: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/list-invites-request
const encoding35 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.includeRevoked ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      includeRevoked: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/list-invites-response.invites
const encoding36_0 = c.array(c.frame(encoding15))

// @bonk-docs-rpc/list-invites-response
const encoding36 = {
  preencode(state, m) {
    encoding36_0.preencode(state, m.invites)
  },
  encode(state, m) {
    encoding36_0.encode(state, m.invites)
  },
  decode(state) {
    const r0 = encoding36_0.decode(state)

    return {
      invites: r0
    }
  }
}

// @bonk-docs-rpc/create-invite-request.roles
const encoding37_1 = encoding1_4

// @bonk-docs-rpc/create-invite-request
const encoding37 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 2 so always one byte

    if (m.roles) encoding37_1.preencode(state, m.roles)
    if (m.expiresAt) c.uint.preencode(state, m.expiresAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.expiresAt ? 2 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.roles) encoding37_1.encode(state, m.roles)
    if (m.expiresAt) c.uint.encode(state, m.expiresAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      roles: (flags & 1) !== 0 ? encoding37_1.decode(state) : null,
      expiresAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/create-invite-response
const encoding38 = {
  preencode(state, m) {
    c.string.preencode(state, m.invite)
    c.string.preencode(state, m.inviteId)
  },
  encode(state, m) {
    c.string.encode(state, m.invite)
    c.string.encode(state, m.inviteId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      invite: r0,
      inviteId: r1
    }
  }
}

// @bonk-docs-rpc/revoke-invite-request
const encoding39 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.inviteId)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.string.encode(state, m.inviteId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      key: r0,
      inviteId: r1
    }
  }
}

// @bonk-docs-rpc/revoke-invite-response
const encoding40 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.revoked ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      revoked: (flags & 1) !== 0
    }
  }
}

// @bonk-docs-rpc/pair-invite-request
const encoding41 = encoding22

// @bonk-docs-rpc/pair-status.doc
const encoding42_3 = encoding21_0

// @bonk-docs-rpc/pair-status
const encoding42 = {
  preencode(state, m) {
    c.string.preencode(state, m.state)
    state.end++ // max flag is 8 so always one byte

    if (m.message) c.string.preencode(state, m.message)
    if (m.progress) c.uint.preencode(state, m.progress)
    if (m.doc) encoding42_3.preencode(state, m.doc)
    if (m.writerKey) c.string.preencode(state, m.writerKey)
  },
  encode(state, m) {
    const flags =
      (m.message ? 1 : 0) |
      (m.progress ? 2 : 0) |
      (m.doc ? 4 : 0) |
      (m.writerKey ? 8 : 0)

    c.string.encode(state, m.state)
    c.uint.encode(state, flags)

    if (m.message) c.string.encode(state, m.message)
    if (m.progress) c.uint.encode(state, m.progress)
    if (m.doc) encoding42_3.encode(state, m.doc)
    if (m.writerKey) c.string.encode(state, m.writerKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      state: r0,
      message: (flags & 1) !== 0 ? c.string.decode(state) : null,
      progress: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      doc: (flags & 4) !== 0 ? encoding42_3.decode(state) : null,
      writerKey: (flags & 8) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/lock-doc-request
const encoding43 = encoding24

// @bonk-docs-rpc/lock-doc-response
const encoding44 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.uint.preencode(state, m.lockedAt)
    c.string.preencode(state, m.lockedBy)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.rev) c.uint.preencode(state, m.rev)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.rev) ? 1 : 0

    c.string.encode(state, m.key)
    c.uint.encode(state, m.lockedAt)
    c.string.encode(state, m.lockedBy)
    c.uint.encode(state, flags)

    if (version >= 2 && m.rev) c.uint.encode(state, m.rev)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      lockedAt: r1,
      lockedBy: r2,
      rev: (version >= 2 && (flags & 1) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs/update
const encoding45 = {
  preencode(state, m) {
    c.uint.preencode(state, m.rev)
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (version >= 4 && m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = (version >= 4 && m.sessionId) ? 1 : 0

    c.uint.encode(state, m.rev)
    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (version >= 4 && m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      rev: r0,
      clientId: r1,
      timestamp: r2,
      data: r3,
      sessionId: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-update-entry
const encoding46 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 3 && m.rev) c.uint.preencode(state, m.rev)
    c.string.preencode(state, m.clientId)
    if (version >= 3 && m.timestamp) c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    const flags =
      ((version >= 3 && m.rev) ? 1 : 0) |
      ((version >= 3 && m.timestamp) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 3 && m.rev) c.uint.encode(state, m.rev)
    c.string.encode(state, m.clientId)
    if (version >= 3 && m.timestamp) c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      rev: (version >= 3 && (flags & 1) !== 0) ? c.uint.decode(state) : 0,
      clientId: c.string.decode(state),
      timestamp: (version >= 3 && (flags & 2) !== 0) ? c.uint.decode(state) : 0,
      data: c.buffer.decode(state)
    }
  }
}

// @bonk-docs-rpc/apply-updates-request
const encoding47 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    encoding47_1.preencode(state, m.updates)
    state.end++ // max flag is 1 so always one byte

    if (version >= 3 && m.clientTime) c.uint.preencode(state, m.clientTime)
  },
  encode(state, m) {
    const flags = (version >= 3 && m.clientTime) ? 1 : 0

    c.string.encode(state, m.key)
    encoding47_1.encode(state, m.updates)
    c.uint.encode(state, flags)

    if (version >= 3 && m.clientTime) c.uint.encode(state, m.clientTime)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding47_1.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      updates: r1,
      clientTime: (version >= 3 && (flags & 1) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs-rpc/apply-updates-response
const encoding48 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (version >= 3 && m.revision) c.uint.preencode(state, m.revision)
    if (version >= 3 && m.error) c.string.preencode(state, m.error)
  },
  encode(state, m) {
    const flags =
      ((version >= 3 && m.accepted) ? 1 : 0) |
      ((version >= 3 && m.revision) ? 2 : 0) |
      ((version >= 3 && m.error) ? 4 : 0)

    c.uint.encode(state, flags)

    if (version >= 3 && m.revision) c.uint.encode(state, m.revision)
    if (version >= 3 && m.error) c.string.encode(state, m.error)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      accepted: (version >= 3 && (flags & 1) !== 0),
      revision: (version >= 3 && (flags & 2) !== 0) ? c.uint.decode(state) : 0,
      error: (version >= 3 && (flags & 4) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/apply-awareness-request
const encoding49 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.buffer.preencode(state, m.update)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.buffer.encode(state, m.update)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      key: r0,
      update: r1
    }
  }
}

// @bonk-docs-rpc/apply-awareness-response
const encoding50 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = (version >= 3 && m.accepted) ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      accepted: (version >= 3 && (flags & 1) !== 0)
    }
  }
}

// @bonk-docs/update-entry
const encoding51 = {
  preencode(state, m) {
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (version >= 5 && m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = (version >= 5 && m.sessionId) ? 1 : 0

    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (version >= 5 && m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      clientId: r0,
      timestamp: r1,
      data: r2,
      sessionId: (version >= 5 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @autobonk/invite/hyperdb#0.roles
const encoding52_4 = encoding1_4

// @autobonk/invite/hyperdb#0
const encoding52 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
    state.end++ // max flag is 8 so always one byte

    if (m.roles) encoding52_4.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) |
      (m.createdBy ? 2 : 0) |
      (m.createdAt ? 4 : 0) |
      (m.revokedAt ? 8 : 0)

    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.roles) encoding52_4.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      invite: r1,
      publicKey: r2,
      expires: r3,
      roles: (flags & 1) !== 0 ? encoding52_4.decode(state) : null,
      createdBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @autobonk/writer/hyperdb#1
const encoding53 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      key: null,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @autobonk/context-init/hyperdb#2
const encoding54 = {
  preencode(state, m) {
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)

    return {
      creatorKey: null,
      index: r1,
      timestamp: r2
    }
  }
}

// @autobonk/role-def/hyperdb#3.permissions
const encoding55_1 = encoding1_4

// @autobonk/role-def/hyperdb#3
const encoding55 = {
  preencode(state, m) {
    encoding55_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    encoding55_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r1 = encoding55_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: null,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @autobonk/acl-entry/hyperdb#4.roles
const encoding56_1 = encoding1_4

// @autobonk/acl-entry/hyperdb#4
const encoding56 = {
  preencode(state, m) {
    encoding56_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    encoding56_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r1 = encoding56_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: null,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @bonk-docs/metadata/hyperdb#5
const encoding57 = {
  preencode(state, m) {
    state.end++ // max flag is 32 so always one byte

    if (m.title) c.string.preencode(state, m.title)
    if (m.description) c.string.preencode(state, m.description)
    c.uint.preencode(state, m.createdAt)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
    if (m.creatorKey) c.fixed32.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.rev)
    if (version >= 2 && m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.fixed32.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    const flags =
      (m.title ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.updatedAt ? 4 : 0) |
      (m.creatorKey ? 8 : 0) |
      ((version >= 2 && m.lockedAt) ? 16 : 0) |
      ((version >= 2 && m.lockedBy) ? 32 : 0)

    c.uint.encode(state, flags)

    if (m.title) c.string.encode(state, m.title)
    if (m.description) c.string.encode(state, m.description)
    c.uint.encode(state, m.createdAt)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
    if (m.creatorKey) c.fixed32.encode(state, m.creatorKey)
    c.uint.encode(state, m.rev)
    if (version >= 2 && m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.fixed32.encode(state, m.lockedBy)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: null,
      title: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      createdAt: c.uint.decode(state),
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      creatorKey: (flags & 8) !== 0 ? c.fixed32.decode(state) : null,
      rev: c.uint.decode(state),
      lockedAt: (version >= 2 && (flags & 16) !== 0) ? c.uint.decode(state) : 0,
      lockedBy: (version >= 2 && (flags & 32) !== 0) ? c.fixed32.decode(state) : null
    }
  }
}

// @bonk-docs/operation/hyperdb#6
const encoding58 = {
  preencode(state, m) {
    c.uint.preencode(state, m.baseRev)
    c.fixed32.preencode(state, m.clientId)
    state.end++ // max flag is 1 so always one byte

    if (m.sessionId) c.fixed32.preencode(state, m.sessionId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    const flags = m.sessionId ? 1 : 0

    c.uint.encode(state, m.baseRev)
    c.fixed32.encode(state, m.clientId)
    c.uint.encode(state, flags)

    if (m.sessionId) c.fixed32.encode(state, m.sessionId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const r1 = c.uint.decode(state)
    const r2 = c.fixed32.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: 0,
      baseRev: r1,
      clientId: r2,
      sessionId: (flags & 1) !== 0 ? c.fixed32.decode(state) : null,
      timestamp: c.uint.decode(state),
      data: c.buffer.decode(state)
    }
  }
}

// @bonk-docs/snapshot/hyperdb#7
const encoding59 = {
  preencode(state, m) {
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 4 so always one byte

    if (m.compression) c.string.preencode(state, m.compression)
    c.buffer.preencode(state, m.data)
    if (m.hash) c.buffer.preencode(state, m.hash)
    if (version >= 3 && m.stateVector) c.buffer.preencode(state, m.stateVector)
  },
  encode(state, m) {
    const flags =
      (m.compression ? 1 : 0) |
      (m.hash ? 2 : 0) |
      ((version >= 3 && m.stateVector) ? 4 : 0)

    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.compression) c.string.encode(state, m.compression)
    c.buffer.encode(state, m.data)
    if (m.hash) c.buffer.encode(state, m.hash)
    if (version >= 3 && m.stateVector) c.buffer.encode(state, m.stateVector)
  },
  decode(state) {
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      rev: 0,
      createdAt: r1,
      compression: (flags & 1) !== 0 ? c.string.decode(state) : null,
      data: c.buffer.decode(state),
      hash: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      stateVector: (version >= 3 && (flags & 4) !== 0) ? c.buffer.decode(state) : null
    }
  }
}

// @local/doc/hyperdb#8
const encoding60 = {
  preencode(state, m) {
    c.string.preencode(state, m.encryptionKey)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 64 so always one byte

    if (m.joinedAt) c.uint.preencode(state, m.joinedAt)
    if (m.title) c.string.preencode(state, m.title)
    if (m.lastRevision) c.uint.preencode(state, m.lastRevision)
    if (m.lastOpenedAt) c.uint.preencode(state, m.lastOpenedAt)
    if (version >= 2 && m.lockedAt) c.uint.preencode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.preencode(state, m.lockedBy)
  },
  encode(state, m) {
    const flags =
      (m.joinedAt ? 1 : 0) |
      (m.isCreator ? 2 : 0) |
      (m.title ? 4 : 0) |
      (m.lastRevision ? 8 : 0) |
      (m.lastOpenedAt ? 16 : 0) |
      ((version >= 2 && m.lockedAt) ? 32 : 0) |
      ((version >= 2 && m.lockedBy) ? 64 : 0)

    c.string.encode(state, m.encryptionKey)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.joinedAt) c.uint.encode(state, m.joinedAt)
    if (m.title) c.string.encode(state, m.title)
    if (m.lastRevision) c.uint.encode(state, m.lastRevision)
    if (m.lastOpenedAt) c.uint.encode(state, m.lastOpenedAt)
    if (version >= 2 && m.lockedAt) c.uint.encode(state, m.lockedAt)
    if (version >= 2 && m.lockedBy) c.string.encode(state, m.lockedBy)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: null,
      encryptionKey: r1,
      createdAt: r2,
      joinedAt: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      isCreator: (flags & 2) !== 0,
      title: (flags & 4) !== 0 ? c.string.decode(state) : null,
      lastRevision: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      lastOpenedAt: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      lockedAt: (version >= 2 && (flags & 32) !== 0) ? c.uint.decode(state) : 0,
      lockedBy: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @local/state/hyperdb#9
const encoding61 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.activeDoc) c.string.preencode(state, m.activeDoc)
    if (m.lastSeenAt) c.uint.preencode(state, m.lastSeenAt)
  },
  encode(state, m) {
    const flags =
      (m.activeDoc ? 1 : 0) |
      (m.lastSeenAt ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.activeDoc) c.string.encode(state, m.activeDoc)
    if (m.lastSeenAt) c.uint.encode(state, m.lastSeenAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: null,
      activeDoc: (flags & 1) !== 0 ? c.string.decode(state) : null,
      lastSeenAt: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @local/profile/hyperdb#10
const encoding62 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.displayName) c.string.preencode(state, m.displayName)
    if (m.color) c.string.preencode(state, m.color)
    if (m.updatedAt) c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.displayName ? 1 : 0) |
      (m.color ? 2 : 0) |
      (m.updatedAt ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.displayName) c.string.encode(state, m.displayName)
    if (m.color) c.string.encode(state, m.color)
    if (m.updatedAt) c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: null,
      displayName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      color: (flags & 2) !== 0 ? c.string.decode(state) : null,
      updatedAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bonk-docs/update/hyperdb#11
const encoding63 = {
  preencode(state, m) {
    c.string.preencode(state, m.clientId)
    c.uint.preencode(state, m.timestamp)
    c.buffer.preencode(state, m.data)
    state.end++ // max flag is 1 so always one byte

    if (version >= 4 && m.sessionId) c.string.preencode(state, m.sessionId)
  },
  encode(state, m) {
    const flags = (version >= 4 && m.sessionId) ? 1 : 0

    c.string.encode(state, m.clientId)
    c.uint.encode(state, m.timestamp)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, flags)

    if (version >= 4 && m.sessionId) c.string.encode(state, m.sessionId)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      rev: 0,
      clientId: r1,
      timestamp: r2,
      data: r3,
      sessionId: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bonk-docs-rpc/doc-update.updates, deferred due to recusive use
const encoding14_12 = c.array(c.frame(encoding46))
// @bonk-docs-rpc/apply-updates-request.updates, deferred due to recusive use
const encoding47_1 = encoding14_12

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autobonk/writer':
      return encoding0
    case '@autobonk/invite':
      return encoding1
    case '@autobonk/revoke-invite':
      return encoding2
    case '@autobonk/context-init':
      return encoding3
    case '@autobonk/role-def':
      return encoding4
    case '@autobonk/acl-entry':
      return encoding5
    case '@bonk-docs/metadata':
      return encoding6
    case '@bonk-docs/operation':
      return encoding7
    case '@bonk-docs/snapshot':
      return encoding8
    case '@local/doc':
      return encoding9
    case '@local/state':
      return encoding10
    case '@local/profile':
      return encoding11
    case '@bonk-docs-rpc/doc-capabilities':
      return encoding12
    case '@bonk-docs-rpc/doc-operation':
      return encoding13
    case '@bonk-docs-rpc/doc-update':
      return encoding14
    case '@bonk-docs-rpc/doc-invite':
      return encoding15
    case '@bonk-docs-rpc/initialize-request':
      return encoding16
    case '@bonk-docs-rpc/initialize-response':
      return encoding17
    case '@bonk-docs-rpc/list-docs-request':
      return encoding18
    case '@bonk-docs-rpc/list-docs-response':
      return encoding19
    case '@bonk-docs-rpc/create-doc-request':
      return encoding20
    case '@bonk-docs-rpc/create-doc-response':
      return encoding21
    case '@bonk-docs-rpc/join-doc-request':
      return encoding22
    case '@bonk-docs-rpc/join-doc-response':
      return encoding23
    case '@bonk-docs-rpc/remove-doc-request':
      return encoding24
    case '@bonk-docs-rpc/remove-doc-response':
      return encoding25
    case '@bonk-docs-rpc/rename-doc-request':
      return encoding26
    case '@bonk-docs-rpc/rename-doc-response':
      return encoding27
    case '@bonk-docs-rpc/get-doc-request':
      return encoding28
    case '@bonk-docs-rpc/get-doc-response':
      return encoding29
    case '@bonk-docs-rpc/watch-doc-request':
      return encoding30
    case '@bonk-docs-rpc/apply-ops-request':
      return encoding31
    case '@bonk-docs-rpc/apply-ops-response':
      return encoding32
    case '@bonk-docs-rpc/update-presence-request':
      return encoding33
    case '@bonk-docs-rpc/update-presence-response':
      return encoding34
    case '@bonk-docs-rpc/list-invites-request':
      return encoding35
    case '@bonk-docs-rpc/list-invites-response':
      return encoding36
    case '@bonk-docs-rpc/create-invite-request':
      return encoding37
    case '@bonk-docs-rpc/create-invite-response':
      return encoding38
    case '@bonk-docs-rpc/revoke-invite-request':
      return encoding39
    case '@bonk-docs-rpc/revoke-invite-response':
      return encoding40
    case '@bonk-docs-rpc/pair-invite-request':
      return encoding41
    case '@bonk-docs-rpc/pair-status':
      return encoding42
    case '@bonk-docs-rpc/lock-doc-request':
      return encoding43
    case '@bonk-docs-rpc/lock-doc-response':
      return encoding44
    case '@bonk-docs/update':
      return encoding45
    case '@bonk-docs-rpc/doc-update-entry':
      return encoding46
    case '@bonk-docs-rpc/apply-updates-request':
      return encoding47
    case '@bonk-docs-rpc/apply-updates-response':
      return encoding48
    case '@bonk-docs-rpc/apply-awareness-request':
      return encoding49
    case '@bonk-docs-rpc/apply-awareness-response':
      return encoding50
    case '@bonk-docs/update-entry':
      return encoding51
    case '@autobonk/invite/hyperdb#0':
      return encoding52
    case '@autobonk/writer/hyperdb#1':
      return encoding53
    case '@autobonk/context-init/hyperdb#2':
      return encoding54
    case '@autobonk/role-def/hyperdb#3':
      return encoding55
    case '@autobonk/acl-entry/hyperdb#4':
      return encoding56
    case '@bonk-docs/metadata/hyperdb#5':
      return encoding57
    case '@bonk-docs/operation/hyperdb#6':
      return encoding58
    case '@bonk-docs/snapshot/hyperdb#7':
      return encoding59
    case '@local/doc/hyperdb#8':
      return encoding60
    case '@local/state/hyperdb#9':
      return encoding61
    case '@local/profile/hyperdb#10':
      return encoding62
    case '@bonk-docs/update/hyperdb#11':
      return encoding63
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
